/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const processSupportTicketParams = zod.object({
  "id": zod.number()
})

export const processSupportTicketBody = zod.object({
  "note": zod.string().optional(),
  "reply": zod.string().optional()
})




export const createSupportTicketBody = zod.object({
  "title": zod.string().min(1),
  "description": zod.string().optional(),
  "type": zod.enum(['BUG_REPORT', 'FEATURE_REQUEST', 'TECHNICAL_SUPPORT', 'COMPLAINT', 'OTHER']),
  "severity": zod.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']),
  "attachmentIds": zod.array(zod.number()).optional()
})

export const closeSupportTicketParams = zod.object({
  "id": zod.number()
})

export const getClientSupportTicketsQueryPageDefault = 0;
export const getClientSupportTicketsQueryPageMin = 0;

export const getClientSupportTicketsQuerySizeDefault = 20;



export const getClientSupportTicketsQueryParams = zod.object({
  "page": zod.number().min(getClientSupportTicketsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getClientSupportTicketsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional()
})

export const getClientSupportTicketByIdParams = zod.object({
  "id": zod.number()
})

export const getAdminSupportTicketsQueryPageDefault = 0;
export const getAdminSupportTicketsQueryPageMin = 0;

export const getAdminSupportTicketsQuerySizeDefault = 20;



export const getAdminSupportTicketsQueryParams = zod.object({
  "page": zod.number().min(getAdminSupportTicketsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getAdminSupportTicketsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional()
})

export const getAdminSupportTicketByIdParams = zod.object({
  "id": zod.number()
})

