/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const getPriceReferencesQueryPageDefault = 0;
export const getPriceReferencesQueryPageMin = 0;

export const getPriceReferencesQuerySizeDefault = 20;

export const getPriceReferencesQueryAllDefault = false;

export const getPriceReferencesQueryParams = zod.object({
  "page": zod.number().min(getPriceReferencesQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getPriceReferencesQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

