/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponsePriceReferenceResponse,
  GetPriceReferencesParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getPriceReferences = (
    params?: GetPriceReferencesParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponsePriceReferenceResponse>(
      {url: `/price-references`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetPriceReferencesQueryKey = (params?: GetPriceReferencesParams,) => {
    return [
    `/price-references`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPriceReferencesQueryOptions = <TData = Awaited<ReturnType<typeof getPriceReferences>>, TError = ErrorType<unknown>>(params?: GetPriceReferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPriceReferencesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPriceReferences>>> = ({ signal }) => getPriceReferences(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPriceReferencesQueryResult = NonNullable<Awaited<ReturnType<typeof getPriceReferences>>>
export type GetPriceReferencesQueryError = ErrorType<unknown>


export function useGetPriceReferences<TData = Awaited<ReturnType<typeof getPriceReferences>>, TError = ErrorType<unknown>>(
 params: undefined |  GetPriceReferencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPriceReferences>>,
          TError,
          Awaited<ReturnType<typeof getPriceReferences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPriceReferences<TData = Awaited<ReturnType<typeof getPriceReferences>>, TError = ErrorType<unknown>>(
 params?: GetPriceReferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPriceReferences>>,
          TError,
          Awaited<ReturnType<typeof getPriceReferences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPriceReferences<TData = Awaited<ReturnType<typeof getPriceReferences>>, TError = ErrorType<unknown>>(
 params?: GetPriceReferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPriceReferences<TData = Awaited<ReturnType<typeof getPriceReferences>>, TError = ErrorType<unknown>>(
 params?: GetPriceReferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPriceReferences>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPriceReferencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




