/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findBookingByIdParams = zod.object({
  "id": zod.number()
})

export const updateBookingParams = zod.object({
  "id": zod.number()
})





export const updateBookingBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().optional(),
  "phone": zod.string().min(1),
  "type": zod.enum(['SELL_ADVICE', 'BUY_ADVICE', 'LEGAL_ADVICE', 'OTHER']),
  "note": zod.string().optional(),
  "date": zod.iso.date(),
  "time": zod.string(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'])
})

export const deleteBookingByIdParams = zod.object({
  "id": zod.number()
})





export const createBookingBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().optional(),
  "phone": zod.string().min(1),
  "type": zod.enum(['SELL_ADVICE', 'BUY_ADVICE', 'LEGAL_ADVICE', 'OTHER']),
  "note": zod.string().optional(),
  "date": zod.iso.date(),
  "time": zod.string(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'])
})

export const findAllBookingQueryPageDefault = 0;
export const findAllBookingQueryPageMin = 0;

export const findAllBookingQuerySizeDefault = 20;

export const findAllBookingQueryAllDefault = false;

export const findAllBookingQueryParams = zod.object({
  "page": zod.number().min(findAllBookingQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllBookingQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkBookingQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

