/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseBookingResponse,
  ApiResponsePageResponseBookingResponse,
  ApiResponseVoid,
  BookingRequest,
  DeleteBulkBookingParams,
  FindAllBookingParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findBookingById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseBookingResponse>(
      {url: `/bookings/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindBookingByIdQueryKey = (id?: number,) => {
    return [
    `/bookings/${id}`
    ] as const;
    }

    
export const getFindBookingByIdQueryOptions = <TData = Awaited<ReturnType<typeof findBookingById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindBookingByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findBookingById>>> = ({ signal }) => findBookingById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindBookingByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findBookingById>>>
export type FindBookingByIdQueryError = ErrorType<unknown>


export function useFindBookingById<TData = Awaited<ReturnType<typeof findBookingById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findBookingById>>,
          TError,
          Awaited<ReturnType<typeof findBookingById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindBookingById<TData = Awaited<ReturnType<typeof findBookingById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findBookingById>>,
          TError,
          Awaited<ReturnType<typeof findBookingById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindBookingById<TData = Awaited<ReturnType<typeof findBookingById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindBookingById<TData = Awaited<ReturnType<typeof findBookingById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findBookingById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindBookingByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateBooking = (
    id: number,
    bookingRequest: BodyType<BookingRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseBookingResponse>(
      {url: `/bookings/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: bookingRequest
    },
      options);
    }
  


export const getUpdateBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingRequest>}, TContext> => {

const mutationKey = ['updateBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBooking>>, {id: number;data: BodyType<BookingRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBooking(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof updateBooking>>>
    export type UpdateBookingMutationBody = BodyType<BookingRequest>
    export type UpdateBookingMutationError = ErrorType<unknown>

    export const useUpdateBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBooking>>,
        TError,
        {id: number;data: BodyType<BookingRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteBookingById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/bookings/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteBookingByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBookingById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBookingById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteBookingById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBookingById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteBookingById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBookingByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBookingById>>>
    
    export type DeleteBookingByIdMutationError = ErrorType<unknown>

    export const useDeleteBookingById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBookingById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBookingById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteBookingByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createBooking = (
    bookingRequest: BodyType<BookingRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseBookingResponse>(
      {url: `/bookings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bookingRequest, signal
    },
      options);
    }
  


export const getCreateBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingRequest>}, TContext> => {

const mutationKey = ['createBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBooking>>, {data: BodyType<BookingRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createBooking(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof createBooking>>>
    export type CreateBookingMutationBody = BodyType<BookingRequest>
    export type CreateBookingMutationError = ErrorType<unknown>

    export const useCreateBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBooking>>,
        TError,
        {data: BodyType<BookingRequest>},
        TContext
      > => {

      const mutationOptions = getCreateBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllBooking = (
    params?: FindAllBookingParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseBookingResponse>(
      {url: `/bookings/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllBookingQueryKey = (params?: FindAllBookingParams,) => {
    return [
    `/bookings/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllBookingQueryOptions = <TData = Awaited<ReturnType<typeof findAllBooking>>, TError = ErrorType<unknown>>(params?: FindAllBookingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllBookingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllBooking>>> = ({ signal }) => findAllBooking(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllBookingQueryResult = NonNullable<Awaited<ReturnType<typeof findAllBooking>>>
export type FindAllBookingQueryError = ErrorType<unknown>


export function useFindAllBooking<TData = Awaited<ReturnType<typeof findAllBooking>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllBookingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllBooking>>,
          TError,
          Awaited<ReturnType<typeof findAllBooking>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllBooking<TData = Awaited<ReturnType<typeof findAllBooking>>, TError = ErrorType<unknown>>(
 params?: FindAllBookingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllBooking>>,
          TError,
          Awaited<ReturnType<typeof findAllBooking>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllBooking<TData = Awaited<ReturnType<typeof findAllBooking>>, TError = ErrorType<unknown>>(
 params?: FindAllBookingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllBooking<TData = Awaited<ReturnType<typeof findAllBooking>>, TError = ErrorType<unknown>>(
 params?: FindAllBookingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllBooking>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllBookingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkBooking = (
    params: DeleteBulkBookingParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/bookings/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkBooking>>, TError,{params: DeleteBulkBookingParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkBooking>>, TError,{params: DeleteBulkBookingParams}, TContext> => {

const mutationKey = ['deleteBulkBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkBooking>>, {params: DeleteBulkBookingParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkBooking(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkBookingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkBooking>>>
    
    export type DeleteBulkBookingMutationError = ErrorType<unknown>

    export const useDeleteBulkBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkBooking>>, TError,{params: DeleteBulkBookingParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkBooking>>,
        TError,
        {params: DeleteBulkBookingParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    