/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseAdminSupportResponse,
  ApiResponsePageResponseSummarySupportResponse,
  ApiResponseSupportResponse,
  ApiResponseVoid,
  GetAdminSupportTicketsParams,
  GetClientSupportTicketsParams,
  ProcessSupportRequest,
  SupportRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const processSupportTicket = (
    id: number,
    processSupportRequest: BodyType<ProcessSupportRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/supports/process/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: processSupportRequest
    },
      options);
    }
  


export const getProcessSupportTicketMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processSupportTicket>>, TError,{id: number;data: BodyType<ProcessSupportRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof processSupportTicket>>, TError,{id: number;data: BodyType<ProcessSupportRequest>}, TContext> => {

const mutationKey = ['processSupportTicket'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processSupportTicket>>, {id: number;data: BodyType<ProcessSupportRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  processSupportTicket(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessSupportTicketMutationResult = NonNullable<Awaited<ReturnType<typeof processSupportTicket>>>
    export type ProcessSupportTicketMutationBody = BodyType<ProcessSupportRequest>
    export type ProcessSupportTicketMutationError = ErrorType<unknown>

    export const useProcessSupportTicket = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processSupportTicket>>, TError,{id: number;data: BodyType<ProcessSupportRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processSupportTicket>>,
        TError,
        {id: number;data: BodyType<ProcessSupportRequest>},
        TContext
      > => {

      const mutationOptions = getProcessSupportTicketMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createSupportTicket = (
    supportRequest: BodyType<SupportRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseSupportResponse>(
      {url: `/supports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: supportRequest, signal
    },
      options);
    }
  


export const getCreateSupportTicketMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSupportTicket>>, TError,{data: BodyType<SupportRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createSupportTicket>>, TError,{data: BodyType<SupportRequest>}, TContext> => {

const mutationKey = ['createSupportTicket'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSupportTicket>>, {data: BodyType<SupportRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createSupportTicket(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSupportTicketMutationResult = NonNullable<Awaited<ReturnType<typeof createSupportTicket>>>
    export type CreateSupportTicketMutationBody = BodyType<SupportRequest>
    export type CreateSupportTicketMutationError = ErrorType<unknown>

    export const useCreateSupportTicket = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSupportTicket>>, TError,{data: BodyType<SupportRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSupportTicket>>,
        TError,
        {data: BodyType<SupportRequest>},
        TContext
      > => {

      const mutationOptions = getCreateSupportTicketMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const closeSupportTicket = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/supports/close/${id}`, method: 'PATCH'
    },
      options);
    }
  


export const getCloseSupportTicketMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeSupportTicket>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof closeSupportTicket>>, TError,{id: number}, TContext> => {

const mutationKey = ['closeSupportTicket'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeSupportTicket>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  closeSupportTicket(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CloseSupportTicketMutationResult = NonNullable<Awaited<ReturnType<typeof closeSupportTicket>>>
    
    export type CloseSupportTicketMutationError = ErrorType<unknown>

    export const useCloseSupportTicket = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeSupportTicket>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeSupportTicket>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getCloseSupportTicketMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getClientSupportTickets = (
    params?: GetClientSupportTicketsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseSummarySupportResponse>(
      {url: `/supports/client`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetClientSupportTicketsQueryKey = (params?: GetClientSupportTicketsParams,) => {
    return [
    `/supports/client`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetClientSupportTicketsQueryOptions = <TData = Awaited<ReturnType<typeof getClientSupportTickets>>, TError = ErrorType<unknown>>(params?: GetClientSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientSupportTicketsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientSupportTickets>>> = ({ signal }) => getClientSupportTickets(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientSupportTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getClientSupportTickets>>>
export type GetClientSupportTicketsQueryError = ErrorType<unknown>


export function useGetClientSupportTickets<TData = Awaited<ReturnType<typeof getClientSupportTickets>>, TError = ErrorType<unknown>>(
 params: undefined |  GetClientSupportTicketsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getClientSupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSupportTickets<TData = Awaited<ReturnType<typeof getClientSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetClientSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getClientSupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSupportTickets<TData = Awaited<ReturnType<typeof getClientSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetClientSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetClientSupportTickets<TData = Awaited<ReturnType<typeof getClientSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetClientSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientSupportTicketsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getClientSupportTicketById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseSupportResponse>(
      {url: `/supports/client/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetClientSupportTicketByIdQueryKey = (id?: number,) => {
    return [
    `/supports/client/${id}`
    ] as const;
    }

    
export const getGetClientSupportTicketByIdQueryOptions = <TData = Awaited<ReturnType<typeof getClientSupportTicketById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientSupportTicketByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientSupportTicketById>>> = ({ signal }) => getClientSupportTicketById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientSupportTicketByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getClientSupportTicketById>>>
export type GetClientSupportTicketByIdQueryError = ErrorType<unknown>


export function useGetClientSupportTicketById<TData = Awaited<ReturnType<typeof getClientSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSupportTicketById>>,
          TError,
          Awaited<ReturnType<typeof getClientSupportTicketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSupportTicketById<TData = Awaited<ReturnType<typeof getClientSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSupportTicketById>>,
          TError,
          Awaited<ReturnType<typeof getClientSupportTicketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSupportTicketById<TData = Awaited<ReturnType<typeof getClientSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetClientSupportTicketById<TData = Awaited<ReturnType<typeof getClientSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientSupportTicketByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAdminSupportTickets = (
    params?: GetAdminSupportTicketsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseSummarySupportResponse>(
      {url: `/supports/admin`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminSupportTicketsQueryKey = (params?: GetAdminSupportTicketsParams,) => {
    return [
    `/supports/admin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminSupportTicketsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSupportTickets>>, TError = ErrorType<unknown>>(params?: GetAdminSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSupportTicketsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSupportTickets>>> = ({ signal }) => getAdminSupportTickets(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSupportTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSupportTickets>>>
export type GetAdminSupportTicketsQueryError = ErrorType<unknown>


export function useGetAdminSupportTickets<TData = Awaited<ReturnType<typeof getAdminSupportTickets>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAdminSupportTicketsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getAdminSupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSupportTickets<TData = Awaited<ReturnType<typeof getAdminSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetAdminSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getAdminSupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSupportTickets<TData = Awaited<ReturnType<typeof getAdminSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetAdminSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAdminSupportTickets<TData = Awaited<ReturnType<typeof getAdminSupportTickets>>, TError = ErrorType<unknown>>(
 params?: GetAdminSupportTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTickets>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSupportTicketsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAdminSupportTicketById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseAdminSupportResponse>(
      {url: `/supports/admin/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminSupportTicketByIdQueryKey = (id?: number,) => {
    return [
    `/supports/admin/${id}`
    ] as const;
    }

    
export const getGetAdminSupportTicketByIdQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSupportTicketByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSupportTicketById>>> = ({ signal }) => getAdminSupportTicketById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSupportTicketByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSupportTicketById>>>
export type GetAdminSupportTicketByIdQueryError = ErrorType<unknown>


export function useGetAdminSupportTicketById<TData = Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSupportTicketById>>,
          TError,
          Awaited<ReturnType<typeof getAdminSupportTicketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSupportTicketById<TData = Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSupportTicketById>>,
          TError,
          Awaited<ReturnType<typeof getAdminSupportTicketById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSupportTicketById<TData = Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAdminSupportTicketById<TData = Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportTicketById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSupportTicketByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




