/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SseEmitter
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const subscribeToFileNotifications = (
    key: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<SseEmitter>(
      {url: `/sse/files/notifications/${key}/subscribe`, method: 'GET', signal
    },
      options);
    }
  



export const getSubscribeToFileNotificationsQueryKey = (key?: string,) => {
    return [
    `/sse/files/notifications/${key}/subscribe`
    ] as const;
    }

    
export const getSubscribeToFileNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError = ErrorType<unknown>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscribeToFileNotificationsQueryKey(key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscribeToFileNotifications>>> = ({ signal }) => subscribeToFileNotifications(key, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubscribeToFileNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof subscribeToFileNotifications>>>
export type SubscribeToFileNotificationsQueryError = ErrorType<unknown>


export function useSubscribeToFileNotifications<TData = Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError = ErrorType<unknown>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeToFileNotifications>>,
          TError,
          Awaited<ReturnType<typeof subscribeToFileNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeToFileNotifications<TData = Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeToFileNotifications>>,
          TError,
          Awaited<ReturnType<typeof subscribeToFileNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeToFileNotifications<TData = Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSubscribeToFileNotifications<TData = Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeToFileNotifications>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubscribeToFileNotificationsQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




