/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseConversationResponse,
  ApiResponsePageResponseConversationResponse,
  ApiResponseVoid,
  GetCurrentUserConversationsParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const participateInConversation = (
    conversationId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/chat/conversations/${conversationId}/participate`, method: 'POST', signal
    },
      options);
    }
  


export const getParticipateInConversationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext> => {

const mutationKey = ['participateInConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof participateInConversation>>, {conversationId: number}> = (props) => {
          const {conversationId} = props ?? {};

          return  participateInConversation(conversationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ParticipateInConversationMutationResult = NonNullable<Awaited<ReturnType<typeof participateInConversation>>>
    
    export type ParticipateInConversationMutationError = ErrorType<unknown>

    export const useParticipateInConversation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof participateInConversation>>,
        TError,
        {conversationId: number},
        TContext
      > => {

      const mutationOptions = getParticipateInConversationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const initializeChat = (
    
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseConversationResponse>(
      {url: `/chat/conversations/initialize`, method: 'POST', signal
    },
      options);
    }
  


export const getInitializeChatMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,void, TContext> => {

const mutationKey = ['initializeChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initializeChat>>, void> = () => {
          

          return  initializeChat(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InitializeChatMutationResult = NonNullable<Awaited<ReturnType<typeof initializeChat>>>
    
    export type InitializeChatMutationError = ErrorType<unknown>

    export const useInitializeChat = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,void, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initializeChat>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getInitializeChatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCurrentUserConversations = (
    params?: GetCurrentUserConversationsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseConversationResponse>(
      {url: `/chat/conversations/me`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCurrentUserConversationsQueryKey = (params?: GetCurrentUserConversationsParams,) => {
    return [
    `/chat/conversations/me`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCurrentUserConversationsQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserConversationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserConversations>>> = ({ signal }) => getCurrentUserConversations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserConversationsQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserConversations>>>
export type GetCurrentUserConversationsQueryError = ErrorType<unknown>


export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params: undefined |  GetCurrentUserConversationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserConversations>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserConversations>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserConversationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




