/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findProvinceByIdParams = zod.object({
  "id": zod.number()
})

export const updateProvinceParams = zod.object({
  "id": zod.number()
})






export const updateProvinceBody = zod.object({
  "name": zod.string().min(1),
  "code": zod.string().min(1),
  "type": zod.string().min(1)
})

export const deleteProvinceByIdParams = zod.object({
  "id": zod.number()
})






export const createProvinceBody = zod.object({
  "name": zod.string().min(1),
  "code": zod.string().min(1),
  "type": zod.string().min(1)
})

export const findAllProvinceQueryPageDefault = 0;
export const findAllProvinceQueryPageMin = 0;

export const findAllProvinceQuerySizeDefault = 20;

export const findAllProvinceQueryAllDefault = false;

export const findAllProvinceQueryParams = zod.object({
  "page": zod.number().min(findAllProvinceQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllProvinceQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkProvinceQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

