/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseProvinceResponse,
  ApiResponseProvinceResponse,
  ApiResponseVoid,
  DeleteBulkProvinceParams,
  FindAllProvinceParams,
  ProvinceRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findProvinceById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResponse>(
      {url: `/provinces/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindProvinceByIdQueryKey = (id?: number,) => {
    return [
    `/provinces/${id}`
    ] as const;
    }

    
export const getFindProvinceByIdQueryOptions = <TData = Awaited<ReturnType<typeof findProvinceById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindProvinceByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findProvinceById>>> = ({ signal }) => findProvinceById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindProvinceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findProvinceById>>>
export type FindProvinceByIdQueryError = ErrorType<unknown>


export function useFindProvinceById<TData = Awaited<ReturnType<typeof findProvinceById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findProvinceById>>,
          TError,
          Awaited<ReturnType<typeof findProvinceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindProvinceById<TData = Awaited<ReturnType<typeof findProvinceById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findProvinceById>>,
          TError,
          Awaited<ReturnType<typeof findProvinceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindProvinceById<TData = Awaited<ReturnType<typeof findProvinceById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindProvinceById<TData = Awaited<ReturnType<typeof findProvinceById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindProvinceByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateProvince = (
    id: number,
    provinceRequest: BodyType<ProvinceRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResponse>(
      {url: `/provinces/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: provinceRequest
    },
      options);
    }
  


export const getUpdateProvinceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: number;data: BodyType<ProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: number;data: BodyType<ProvinceRequest>}, TContext> => {

const mutationKey = ['updateProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProvince>>, {id: number;data: BodyType<ProvinceRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProvince(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof updateProvince>>>
    export type UpdateProvinceMutationBody = BodyType<ProvinceRequest>
    export type UpdateProvinceMutationError = ErrorType<unknown>

    export const useUpdateProvince = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: number;data: BodyType<ProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProvince>>,
        TError,
        {id: number;data: BodyType<ProvinceRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateProvinceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteProvinceById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/provinces/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteProvinceByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProvinceById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProvinceById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProvinceById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProvinceById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProvinceById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProvinceByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProvinceById>>>
    
    export type DeleteProvinceByIdMutationError = ErrorType<unknown>

    export const useDeleteProvinceById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProvinceById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProvinceById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteProvinceByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createProvince = (
    provinceRequest: BodyType<ProvinceRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResponse>(
      {url: `/provinces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: provinceRequest, signal
    },
      options);
    }
  


export const getCreateProvinceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<ProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<ProvinceRequest>}, TContext> => {

const mutationKey = ['createProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProvince>>, {data: BodyType<ProvinceRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createProvince(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof createProvince>>>
    export type CreateProvinceMutationBody = BodyType<ProvinceRequest>
    export type CreateProvinceMutationError = ErrorType<unknown>

    export const useCreateProvince = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<ProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProvince>>,
        TError,
        {data: BodyType<ProvinceRequest>},
        TContext
      > => {

      const mutationOptions = getCreateProvinceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllProvince = (
    params?: FindAllProvinceParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseProvinceResponse>(
      {url: `/provinces/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllProvinceQueryKey = (params?: FindAllProvinceParams,) => {
    return [
    `/provinces/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllProvinceQueryOptions = <TData = Awaited<ReturnType<typeof findAllProvince>>, TError = ErrorType<unknown>>(params?: FindAllProvinceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllProvinceQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllProvince>>> = ({ signal }) => findAllProvince(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllProvinceQueryResult = NonNullable<Awaited<ReturnType<typeof findAllProvince>>>
export type FindAllProvinceQueryError = ErrorType<unknown>


export function useFindAllProvince<TData = Awaited<ReturnType<typeof findAllProvince>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllProvinceParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllProvince>>,
          TError,
          Awaited<ReturnType<typeof findAllProvince>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllProvince<TData = Awaited<ReturnType<typeof findAllProvince>>, TError = ErrorType<unknown>>(
 params?: FindAllProvinceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllProvince>>,
          TError,
          Awaited<ReturnType<typeof findAllProvince>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllProvince<TData = Awaited<ReturnType<typeof findAllProvince>>, TError = ErrorType<unknown>>(
 params?: FindAllProvinceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllProvince<TData = Awaited<ReturnType<typeof findAllProvince>>, TError = ErrorType<unknown>>(
 params?: FindAllProvinceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProvince>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllProvinceQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkProvince = (
    params: DeleteBulkProvinceParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/provinces/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkProvinceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProvince>>, TError,{params: DeleteBulkProvinceParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProvince>>, TError,{params: DeleteBulkProvinceParams}, TContext> => {

const mutationKey = ['deleteBulkProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkProvince>>, {params: DeleteBulkProvinceParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkProvince(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkProvince>>>
    
    export type DeleteBulkProvinceMutationError = ErrorType<unknown>

    export const useDeleteBulkProvince = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProvince>>, TError,{params: DeleteBulkProvinceParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkProvince>>,
        TError,
        {params: DeleteBulkProvinceParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkProvinceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    