/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


export const findUserByIdParams = zod.object({
  "id": zod.number()
})

export const updateUserParams = zod.object({
  "id": zod.number()
})

export const updateUserBody = zod.object({
  "fullName": zod.string().optional(),
  "email": zod.string().min(1),
  "phone": zod.string().min(1),
  "password": zod.string().optional(),
  "emailVerified": zod.boolean().optional(),
  "phoneVerified": zod.boolean().optional(),
  "status": zod.enum(['UNVERIFIED', 'ACTIVE', 'INACTIVE', 'BLOCKED']).optional(),
  "roleId": zod.number()
})

export const deleteUserByIdParams = zod.object({
  "id": zod.number()
})

export const createUserBody = zod.object({
  "fullName": zod.string().optional(),
  "email": zod.string().min(1),
  "phone": zod.string().min(1),
  "password": zod.string().optional(),
  "emailVerified": zod.boolean().optional(),
  "phoneVerified": zod.boolean().optional(),
  "status": zod.enum(['UNVERIFIED', 'ACTIVE', 'INACTIVE', 'BLOCKED']).optional(),
  "roleId": zod.number()
})

export const findAllUserQueryPageDefault = 0;
export const findAllUserQueryPageMin = 0;
export const findAllUserQuerySizeDefault = 20;

export const findAllUserQueryParams = zod.object({
  "page": zod.number().min(findAllUserQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllUserQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional()
})

export const deleteBulkUserQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

