/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';






export const verifyOtpBody = zod.object({
  "destination": zod.string().min(1),
  "otp": zod.string().min(1),
  "purpose": zod.enum(['REGISTRATION', 'PASSWORD_RESET', 'EMAIL_VERIFICATION', 'PHONE_VERIFICATION']).optional()
})




export const verifyEmailBody = zod.object({
  "code": zod.string().min(1)
})




export const sendOtpBody = zod.object({
  "destination": zod.string().min(1),
  "purpose": zod.enum(['REGISTRATION', 'PASSWORD_RESET', 'EMAIL_VERIFICATION', 'PHONE_VERIFICATION'])
})





export const resetPasswordBody = zod.object({
  "verificationCode": zod.string().min(1),
  "newPassword": zod.string().min(1)
})






export const registerBody = zod.object({
  "verificationToken": zod.string().min(1),
  "email": zod.string().optional(),
  "fullName": zod.string().min(1),
  "password": zod.string().min(1)
})




export const refreshTokenBody = zod.object({
  "refreshToken": zod.string().min(1)
})





export const updateCurrentUserBody = zod.object({
  "fullName": zod.string().optional(),
  "email": zod.string().min(1),
  "phone": zod.string().min(1)
})







export const updateCurrentUserAvatarBody = zod.object({
  "publicId": zod.string().min(1),
  "version": zod.number(),
  "signature": zod.string().optional(),
  "secureUrl": zod.string().min(1),
  "width": zod.number(),
  "height": zod.number(),
  "format": zod.string().min(1),
  "resourceType": zod.string().min(1),
  "bytes": zod.number(),
  "purpose": zod.enum(['AVATAR', 'THUMBNAIL', 'BANNER', 'VIDEO', 'GALLERY'])
})




export const logoutBody = zod.object({
  "refreshToken": zod.string().min(1)
})





export const loginBody = zod.object({
  "credential": zod.string().min(1),
  "password": zod.string().min(1)
})





export const changePasswordBody = zod.object({
  "oldPassword": zod.string().min(1),
  "newPassword": zod.string().min(1)
})

