/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseConversationResponse,
  ApiResponsePageResponseConversationResponse,
  ApiResponseVoid,
  ChatInitilizeRequest,
  FindAllConversationsParams,
  GetCurrentUserConversationsParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const participateInConversation = (
    conversationId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/chat/conversations/${conversationId}/participate`, method: 'POST', signal
    },
      options);
    }
  


export const getParticipateInConversationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext> => {

const mutationKey = ['participateInConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof participateInConversation>>, {conversationId: number}> = (props) => {
          const {conversationId} = props ?? {};

          return  participateInConversation(conversationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ParticipateInConversationMutationResult = NonNullable<Awaited<ReturnType<typeof participateInConversation>>>
    
    export type ParticipateInConversationMutationError = ErrorType<unknown>

    export const useParticipateInConversation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof participateInConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof participateInConversation>>,
        TError,
        {conversationId: number},
        TContext
      > => {

      const mutationOptions = getParticipateInConversationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const closeConversation = (
    conversationId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/chat/conversations/${conversationId}/close`, method: 'POST', signal
    },
      options);
    }
  


export const getCloseConversationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof closeConversation>>, TError,{conversationId: number}, TContext> => {

const mutationKey = ['closeConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeConversation>>, {conversationId: number}> = (props) => {
          const {conversationId} = props ?? {};

          return  closeConversation(conversationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CloseConversationMutationResult = NonNullable<Awaited<ReturnType<typeof closeConversation>>>
    
    export type CloseConversationMutationError = ErrorType<unknown>

    export const useCloseConversation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeConversation>>, TError,{conversationId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeConversation>>,
        TError,
        {conversationId: number},
        TContext
      > => {

      const mutationOptions = getCloseConversationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const initializeChat = (
    chatInitilizeRequest: BodyType<ChatInitilizeRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseConversationResponse>(
      {url: `/chat/conversations/initialize`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatInitilizeRequest, signal
    },
      options);
    }
  


export const getInitializeChatMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,{data: BodyType<ChatInitilizeRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,{data: BodyType<ChatInitilizeRequest>}, TContext> => {

const mutationKey = ['initializeChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initializeChat>>, {data: BodyType<ChatInitilizeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  initializeChat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InitializeChatMutationResult = NonNullable<Awaited<ReturnType<typeof initializeChat>>>
    export type InitializeChatMutationBody = BodyType<ChatInitilizeRequest>
    export type InitializeChatMutationError = ErrorType<unknown>

    export const useInitializeChat = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initializeChat>>, TError,{data: BodyType<ChatInitilizeRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initializeChat>>,
        TError,
        {data: BodyType<ChatInitilizeRequest>},
        TContext
      > => {

      const mutationOptions = getInitializeChatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllConversations = (
    params?: FindAllConversationsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseConversationResponse>(
      {url: `/chat/conversations`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllConversationsQueryKey = (params?: FindAllConversationsParams,) => {
    return [
    `/chat/conversations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllConversationsQueryOptions = <TData = Awaited<ReturnType<typeof findAllConversations>>, TError = ErrorType<unknown>>(params?: FindAllConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllConversationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllConversations>>> = ({ signal }) => findAllConversations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllConversationsQueryResult = NonNullable<Awaited<ReturnType<typeof findAllConversations>>>
export type FindAllConversationsQueryError = ErrorType<unknown>


export function useFindAllConversations<TData = Awaited<ReturnType<typeof findAllConversations>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllConversationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllConversations>>,
          TError,
          Awaited<ReturnType<typeof findAllConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllConversations<TData = Awaited<ReturnType<typeof findAllConversations>>, TError = ErrorType<unknown>>(
 params?: FindAllConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllConversations>>,
          TError,
          Awaited<ReturnType<typeof findAllConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllConversations<TData = Awaited<ReturnType<typeof findAllConversations>>, TError = ErrorType<unknown>>(
 params?: FindAllConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllConversations<TData = Awaited<ReturnType<typeof findAllConversations>>, TError = ErrorType<unknown>>(
 params?: FindAllConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllConversationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getConversationById = (
    conversationId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseConversationResponse>(
      {url: `/chat/conversations/${conversationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetConversationByIdQueryKey = (conversationId?: number,) => {
    return [
    `/chat/conversations/${conversationId}`
    ] as const;
    }

    
export const getGetConversationByIdQueryOptions = <TData = Awaited<ReturnType<typeof getConversationById>>, TError = ErrorType<unknown>>(conversationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConversationByIdQueryKey(conversationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConversationById>>> = ({ signal }) => getConversationById(conversationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(conversationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConversationByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getConversationById>>>
export type GetConversationByIdQueryError = ErrorType<unknown>


export function useGetConversationById<TData = Awaited<ReturnType<typeof getConversationById>>, TError = ErrorType<unknown>>(
 conversationId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationById>>,
          TError,
          Awaited<ReturnType<typeof getConversationById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationById<TData = Awaited<ReturnType<typeof getConversationById>>, TError = ErrorType<unknown>>(
 conversationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationById>>,
          TError,
          Awaited<ReturnType<typeof getConversationById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationById<TData = Awaited<ReturnType<typeof getConversationById>>, TError = ErrorType<unknown>>(
 conversationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConversationById<TData = Awaited<ReturnType<typeof getConversationById>>, TError = ErrorType<unknown>>(
 conversationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConversationByIdQueryOptions(conversationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCurrentUserConversations = (
    params?: GetCurrentUserConversationsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseConversationResponse>(
      {url: `/chat/conversations/me`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCurrentUserConversationsQueryKey = (params?: GetCurrentUserConversationsParams,) => {
    return [
    `/chat/conversations/me`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCurrentUserConversationsQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserConversationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserConversations>>> = ({ signal }) => getCurrentUserConversations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserConversationsQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserConversations>>>
export type GetCurrentUserConversationsQueryError = ErrorType<unknown>


export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params: undefined |  GetCurrentUserConversationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserConversations>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserConversations>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCurrentUserConversations<TData = Awaited<ReturnType<typeof getCurrentUserConversations>>, TError = ErrorType<unknown>>(
 params?: GetCurrentUserConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserConversations>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserConversationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




