/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const participateInConversationParams = zod.object({
  "conversationId": zod.number()
})

export const closeConversationParams = zod.object({
  "conversationId": zod.number()
})

export const initializeChatBody = zod.object({
  "contextId": zod.number().optional()
})

export const findAllConversationsQueryPageDefault = 0;
export const findAllConversationsQueryPageMin = 0;

export const findAllConversationsQuerySizeDefault = 20;



export const findAllConversationsQueryParams = zod.object({
  "page": zod.number().min(findAllConversationsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllConversationsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const getConversationByIdParams = zod.object({
  "conversationId": zod.number()
})

export const getCurrentUserConversationsQueryPageDefault = 0;
export const getCurrentUserConversationsQueryPageMin = 0;

export const getCurrentUserConversationsQuerySizeDefault = 20;



export const getCurrentUserConversationsQueryParams = zod.object({
  "page": zod.number().min(getCurrentUserConversationsQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getCurrentUserConversationsQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

