/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminSupportResponseSeverity = typeof AdminSupportResponseSeverity[keyof typeof AdminSupportResponseSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminSupportResponseSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;
