/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WishResponse } from './wishResponse';
import type { ApiResponseWishResponseErrors } from './apiResponseWishResponseErrors';

export interface ApiResponseWishResponse {
  code?: number;
  message?: string;
  data?: WishResponse;
  errors?: ApiResponseWishResponseErrors;
  timestamp?: string;
}
