/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminSupportResponse } from './adminSupportResponse';
import type { ApiResponseAdminSupportResponseErrors } from './apiResponseAdminSupportResponseErrors';

export interface ApiResponseAdminSupportResponse {
  code?: number;
  message?: string;
  data?: AdminSupportResponse;
  errors?: ApiResponseAdminSupportResponseErrors;
  timestamp?: string;
}
