/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ContentBlockResponse } from './contentBlockResponse';
import type { ApiResponseListContentBlockResponseErrors } from './apiResponseListContentBlockResponseErrors';

export interface ApiResponseListContentBlockResponse {
  code?: number;
  message?: string;
  data?: ContentBlockResponse[];
  errors?: ApiResponseListContentBlockResponseErrors;
  timestamp?: string;
}
