/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PresignedURLResponse } from './presignedURLResponse';
import type { ApiResponsePresignedURLResponseErrors } from './apiResponsePresignedURLResponseErrors';

export interface ApiResponsePresignedURLResponse {
  code?: number;
  message?: string;
  data?: PresignedURLResponse;
  errors?: ApiResponsePresignedURLResponseErrors;
  timestamp?: string;
}
