/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponsePropertyResponse } from './pageResponsePropertyResponse';
import type { ApiResponsePageResponsePropertyResponseErrors } from './apiResponsePageResponsePropertyResponseErrors';

export interface ApiResponsePageResponsePropertyResponse {
  code?: number;
  message?: string;
  data?: PageResponsePropertyResponse;
  errors?: ApiResponsePageResponsePropertyResponseErrors;
  timestamp?: string;
}
