/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookingResponse } from './bookingResponse';
import type { ApiResponseBookingResponseErrors } from './apiResponseBookingResponseErrors';

export interface ApiResponseBookingResponse {
  code?: number;
  message?: string;
  data?: BookingResponse;
  errors?: ApiResponseBookingResponseErrors;
  timestamp?: string;
}
