/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseUserResponse } from './pageResponseUserResponse';
import type { ApiResponsePageResponseUserResponseErrors } from './apiResponsePageResponseUserResponseErrors';

export interface ApiResponsePageResponseUserResponse {
  code?: number;
  message?: string;
  data?: PageResponseUserResponse;
  errors?: ApiResponsePageResponseUserResponseErrors;
  timestamp?: string;
}
