/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyResponse } from './propertyResponse';
import type { ApiResponseListPropertyResponseErrors } from './apiResponseListPropertyResponseErrors';

export interface ApiResponseListPropertyResponse {
  code?: number;
  message?: string;
  data?: PropertyResponse[];
  errors?: ApiResponseListPropertyResponseErrors;
  timestamp?: string;
}
