/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseBookingResponse } from './pageResponseBookingResponse';
import type { ApiResponsePageResponseBookingResponseErrors } from './apiResponsePageResponseBookingResponseErrors';

export interface ApiResponsePageResponseBookingResponse {
  code?: number;
  message?: string;
  data?: PageResponseBookingResponse;
  errors?: ApiResponsePageResponseBookingResponseErrors;
  timestamp?: string;
}
