/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoleResponse } from './roleResponse';
import type { ApiResponseRoleResponseErrors } from './apiResponseRoleResponseErrors';

export interface ApiResponseRoleResponse {
  code?: number;
  message?: string;
  data?: RoleResponse;
  errors?: ApiResponseRoleResponseErrors;
  timestamp?: string;
}
