/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SupportTicketProjection } from './supportTicketProjection';
import type { ApiResponseSupportTicketProjectionErrors } from './apiResponseSupportTicketProjectionErrors';

export interface ApiResponseSupportTicketProjection {
  code?: number;
  message?: string;
  data?: SupportTicketProjection;
  errors?: ApiResponseSupportTicketProjectionErrors;
  timestamp?: string;
}
