/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VerifyOtpResponse } from './verifyOtpResponse';
import type { ApiResponseVerifyOtpResponseErrors } from './apiResponseVerifyOtpResponseErrors';

export interface ApiResponseVerifyOtpResponse {
  code?: number;
  message?: string;
  data?: VerifyOtpResponse;
  errors?: ApiResponseVerifyOtpResponseErrors;
  timestamp?: string;
}
