/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListStringErrors } from './apiResponseListStringErrors';

export interface ApiResponseListString {
  code?: number;
  message?: string;
  data?: string[];
  errors?: ApiResponseListStringErrors;
  timestamp?: string;
}
