/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseSummarySupportResponse } from './pageResponseSummarySupportResponse';
import type { ApiResponsePageResponseSummarySupportResponseErrors } from './apiResponsePageResponseSummarySupportResponseErrors';

export interface ApiResponsePageResponseSummarySupportResponse {
  code?: number;
  message?: string;
  data?: PageResponseSummarySupportResponse;
  errors?: ApiResponsePageResponseSummarySupportResponseErrors;
  timestamp?: string;
}
