/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseProvinceResponse } from './pageResponseProvinceResponse';
import type { ApiResponsePageResponseProvinceResponseErrors } from './apiResponsePageResponseProvinceResponseErrors';

export interface ApiResponsePageResponseProvinceResponse {
  code?: number;
  message?: string;
  data?: PageResponseProvinceResponse;
  errors?: ApiResponsePageResponseProvinceResponseErrors;
  timestamp?: string;
}
