/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MediaResponse } from './mediaResponse';
import type { ApiResponseMediaResponseErrors } from './apiResponseMediaResponseErrors';

export interface ApiResponseMediaResponse {
  code?: number;
  message?: string;
  data?: MediaResponse;
  errors?: ApiResponseMediaResponseErrors;
  timestamp?: string;
}
