/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginResponse } from './loginResponse';
import type { ApiResponseLoginResponseErrors } from './apiResponseLoginResponseErrors';

export interface ApiResponseLoginResponse {
  code?: number;
  message?: string;
  data?: LoginResponse;
  errors?: ApiResponseLoginResponseErrors;
  timestamp?: string;
}
