/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProvinceResponse } from './provinceResponse';
import type { ApiResponseProvinceResponseErrors } from './apiResponseProvinceResponseErrors';

export interface ApiResponseProvinceResponse {
  code?: number;
  message?: string;
  data?: ProvinceResponse;
  errors?: ApiResponseProvinceResponseErrors;
  timestamp?: string;
}
