/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WardResponse } from './wardResponse';
import type { ApiResponseWardResponseErrors } from './apiResponseWardResponseErrors';

export interface ApiResponseWardResponse {
  code?: number;
  message?: string;
  data?: WardResponse;
  errors?: ApiResponseWardResponseErrors;
  timestamp?: string;
}
