/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponsePriceReferenceResponse } from './pageResponsePriceReferenceResponse';
import type { ApiResponsePageResponsePriceReferenceResponseErrors } from './apiResponsePageResponsePriceReferenceResponseErrors';

export interface ApiResponsePageResponsePriceReferenceResponse {
  code?: number;
  message?: string;
  data?: PageResponsePriceReferenceResponse;
  errors?: ApiResponsePageResponsePriceReferenceResponseErrors;
  timestamp?: string;
}
