/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { StatisticResponse } from './statisticResponse';
import type { ApiResponseStatisticResponseErrors } from './apiResponseStatisticResponseErrors';

export interface ApiResponseStatisticResponse {
  code?: number;
  message?: string;
  data?: StatisticResponse;
  errors?: ApiResponseStatisticResponseErrors;
  timestamp?: string;
}
