/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyResponse } from './propertyResponse';
import type { ApiResponsePropertyResponseErrors } from './apiResponsePropertyResponseErrors';

export interface ApiResponsePropertyResponse {
  code?: number;
  message?: string;
  data?: PropertyResponse;
  errors?: ApiResponsePropertyResponseErrors;
  timestamp?: string;
}
