/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseWishResponse } from './pageResponseWishResponse';
import type { ApiResponsePageResponseWishResponseErrors } from './apiResponsePageResponseWishResponseErrors';

export interface ApiResponsePageResponseWishResponse {
  code?: number;
  message?: string;
  data?: PageResponseWishResponse;
  errors?: ApiResponsePageResponseWishResponseErrors;
  timestamp?: string;
}
