/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PresignedUploadResponse } from './presignedUploadResponse';
import type { ApiResponsePresignedUploadResponseErrors } from './apiResponsePresignedUploadResponseErrors';

export interface ApiResponsePresignedUploadResponse {
  code?: number;
  message?: string;
  data?: PresignedUploadResponse;
  errors?: ApiResponsePresignedUploadResponseErrors;
  timestamp?: string;
}
