/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionResponse } from './permissionResponse';
import type { ApiResponsePermissionResponseErrors } from './apiResponsePermissionResponseErrors';

export interface ApiResponsePermissionResponse {
  code?: number;
  message?: string;
  data?: PermissionResponse;
  errors?: ApiResponsePermissionResponseErrors;
  timestamp?: string;
}
