/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseMessageResponse } from './pageResponseMessageResponse';
import type { ApiResponsePageResponseMessageResponseErrors } from './apiResponsePageResponseMessageResponseErrors';

export interface ApiResponsePageResponseMessageResponse {
  code?: number;
  message?: string;
  data?: PageResponseMessageResponse;
  errors?: ApiResponsePageResponseMessageResponseErrors;
  timestamp?: string;
}
