/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponsePermissionResponse } from './pageResponsePermissionResponse';
import type { ApiResponsePageResponsePermissionResponseErrors } from './apiResponsePageResponsePermissionResponseErrors';

export interface ApiResponsePageResponsePermissionResponse {
  code?: number;
  message?: string;
  data?: PageResponsePermissionResponse;
  errors?: ApiResponsePageResponsePermissionResponseErrors;
  timestamp?: string;
}
