/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';
import type { ApiResponseUserResponseErrors } from './apiResponseUserResponseErrors';

export interface ApiResponseUserResponse {
  code?: number;
  message?: string;
  data?: UserResponse;
  errors?: ApiResponseUserResponseErrors;
  timestamp?: string;
}
