/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ConversationResponse } from './conversationResponse';
import type { ApiResponseConversationResponseErrors } from './apiResponseConversationResponseErrors';

export interface ApiResponseConversationResponse {
  code?: number;
  message?: string;
  data?: ConversationResponse;
  errors?: ApiResponseConversationResponseErrors;
  timestamp?: string;
}
