/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadSignatureResponse } from './uploadSignatureResponse';
import type { ApiResponseUploadSignatureResponseErrors } from './apiResponseUploadSignatureResponseErrors';

export interface ApiResponseUploadSignatureResponse {
  code?: number;
  message?: string;
  data?: UploadSignatureResponse;
  errors?: ApiResponseUploadSignatureResponseErrors;
  timestamp?: string;
}
