/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponsePropertyTypeResponse } from './pageResponsePropertyTypeResponse';
import type { ApiResponsePageResponsePropertyTypeResponseErrors } from './apiResponsePageResponsePropertyTypeResponseErrors';

export interface ApiResponsePageResponsePropertyTypeResponse {
  code?: number;
  message?: string;
  data?: PageResponsePropertyTypeResponse;
  errors?: ApiResponsePageResponsePropertyTypeResponseErrors;
  timestamp?: string;
}
