/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SupportResponse } from './supportResponse';
import type { ApiResponseSupportResponseErrors } from './apiResponseSupportResponseErrors';

export interface ApiResponseSupportResponse {
  code?: number;
  message?: string;
  data?: SupportResponse;
  errors?: ApiResponseSupportResponseErrors;
  timestamp?: string;
}
