/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseRoleResponse } from './pageResponseRoleResponse';
import type { ApiResponsePageResponseRoleResponseErrors } from './apiResponsePageResponseRoleResponseErrors';

export interface ApiResponsePageResponseRoleResponse {
  code?: number;
  message?: string;
  data?: PageResponseRoleResponse;
  errors?: ApiResponsePageResponseRoleResponseErrors;
  timestamp?: string;
}
