/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseWardResponse } from './pageResponseWardResponse';
import type { ApiResponsePageResponseWardResponseErrors } from './apiResponsePageResponseWardResponseErrors';

export interface ApiResponsePageResponseWardResponse {
  code?: number;
  message?: string;
  data?: PageResponseWardResponse;
  errors?: ApiResponsePageResponseWardResponseErrors;
  timestamp?: string;
}
