/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseConversationResponse } from './pageResponseConversationResponse';
import type { ApiResponsePageResponseConversationResponseErrors } from './apiResponsePageResponseConversationResponseErrors';

export interface ApiResponsePageResponseConversationResponse {
  code?: number;
  message?: string;
  data?: PageResponseConversationResponse;
  errors?: ApiResponsePageResponseConversationResponseErrors;
  timestamp?: string;
}
