/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BaseUserRequest {
  fullName?: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  phone: string;
  avatarId?: number;
}
