/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { JsonNode } from './jsonNode';

export interface ContentBlockRequest {
  fileId?: number;
  metadata?: JsonNode;
}
