/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ConversationResponseStatus = typeof ConversationResponseStatus[keyof typeof ConversationResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationResponseStatus = {
  PENDING: 'PENDING',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
