/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ConversationResponseStatus } from './conversationResponseStatus';
import type { ParticipantResponse } from './participantResponse';

export interface ConversationResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  contextId?: number;
  status?: ConversationResponseStatus;
  lastMessageAt?: string;
  participants?: ParticipantResponse[];
}
