/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ConversationStatus = typeof ConversationStatus[keyof typeof ConversationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationStatus = {
  PENDING: 'PENDING',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
