/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DataPointStringLong } from './dataPointStringLong';

export interface CountMetric {
  currentCount?: number;
  percentageChange?: number;
  dataPoints?: DataPointStringLong[];
}
