/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetStatisticsGranularity } from './getStatisticsGranularity';

export type GetStatisticsParams = {
startDate?: string;
endDate?: string;
granularity?: GetStatisticsGranularity;
};
