/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetStatisticsGranularity = typeof GetStatisticsGranularity[keyof typeof GetStatisticsGranularity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetStatisticsGranularity = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
