/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './deleteBulkPermissionParams';
export * from './deleteBulkRoleParams';
export * from './findAllPermissionParams';
export * from './findAllRoleParams';
export * from './pageResponsePermissionResponseDTO';
export * from './pageResponseRoleResponseDTO';
export * from './permissionRequestDTO';
export * from './permissionRequestDTOAction';
export * from './permissionResponseDTO';
export * from './permissionResponseDTOAction';
export * from './roleRequestDTO';
export * from './roleResponseDTO';