/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MediaResponsePurpose = typeof MediaResponsePurpose[keyof typeof MediaResponsePurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaResponsePurpose = {
  AVATAR: 'AVATAR',
  THUMBNAIL: 'THUMBNAIL',
  BANNER: 'BANNER',
  VIDEO: 'VIDEO',
  GALLERY: 'GALLERY',
} as const;
