/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MediaResponsePurpose } from './mediaResponsePurpose';

export interface MediaResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  publicId?: string;
  secureUrl?: string;
  width?: number;
  height?: number;
  resourceType?: string;
  format?: string;
  purpose?: MediaResponsePurpose;
  bytes?: number;
}
