/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Conversation } from './conversation';
import type { UserResponse } from './userResponse';

export interface MessageResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  conversation?: Conversation;
  sender?: UserResponse;
  content?: string;
}
