/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyResponse } from './propertyResponse';

export interface PageResponsePropertyResponse {
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  numberOfElements?: number;
  content?: PropertyResponse[];
}
