/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionResponseDTO } from './permissionResponseDTO';

export interface PageResponsePermissionResponseDTO {
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  numberOfElements?: number;
  content?: PermissionResponseDTO[];
}
