/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyTypeResponse } from './propertyTypeResponse';

export interface PageResponsePropertyTypeResponse {
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  numberOfElements?: number;
  content?: PropertyTypeResponse[];
}
