/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoleResponseDTO } from './roleResponseDTO';

export interface PageResponseRoleResponseDTO {
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  numberOfElements?: number;
  content?: RoleResponseDTO[];
}
