/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionRequestAction } from './permissionRequestAction';

export interface PermissionRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  resource: string;
  action: PermissionRequestAction;
}
