/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PermissionRequestAction = typeof PermissionRequestAction[keyof typeof PermissionRequestAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionRequestAction = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
