/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PermissionResponseAction = typeof PermissionResponseAction[keyof typeof PermissionResponseAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionResponseAction = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
