/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PermissionRequestMethod = typeof PermissionRequestMethod[keyof typeof PermissionRequestMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionRequestMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
  OPTIONS: 'OPTIONS',
  HEAD: 'HEAD',
} as const;
