/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionResponseAction } from './permissionResponseAction';

export interface PermissionResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  name?: string;
  resource?: string;
  action?: PermissionResponseAction;
}
