/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionRequestMethod } from './permissionRequestMethod';

export interface PermissionRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  resource: string;
  /** @minLength 1 */
  urlPattern: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  code: string;
  method: PermissionRequestMethod;
}
