/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionResponseMethod } from './permissionResponseMethod';

export interface PermissionResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  name?: string;
  resource?: string;
  urlPattern?: string;
  method?: PermissionResponseMethod;
}
