/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionRequestDTOAction } from './permissionRequestDTOAction';

export interface PermissionRequestDTO {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  resource: string;
  action: PermissionRequestDTOAction;
}
