/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PermissionRequestDTOAction = typeof PermissionRequestDTOAction[keyof typeof PermissionRequestDTOAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionRequestDTOAction = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
