/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PermissionResponseMethod = typeof PermissionResponseMethod[keyof typeof PermissionResponseMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionResponseMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
  OPTIONS: 'OPTIONS',
  HEAD: 'HEAD',
} as const;
