/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PresignedDownloadRequest {
  /** @minLength 1 */
  objectKey: string;
  options?: string;
}
