/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PresignedUploadRequestPurpose = typeof PresignedUploadRequestPurpose[keyof typeof PresignedUploadRequestPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PresignedUploadRequestPurpose = {
  PROPERTY_FILE: 'PROPERTY_FILE',
  PROPERTY_THUMBNAIL: 'PROPERTY_THUMBNAIL',
  PROPERTY_GALLERY: 'PROPERTY_GALLERY',
  CHAT_FILE: 'CHAT_FILE',
  AVATAR: 'AVATAR',
  CAROUSEL_IMAGE: 'CAROUSEL_IMAGE',
  SUPPORT_TICKET_ATTACHMENT: 'SUPPORT_TICKET_ATTACHMENT',
} as const;
