/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WardResponse } from './wardResponse';
import type { PropertyTypeResponse } from './propertyTypeResponse';

export interface PriceReferenceResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  ward?: WardResponse;
  propertyType?: PropertyTypeResponse;
  averagePrice?: number;
  maxPrice?: number;
  minPrice?: number;
  count?: number;
}
