/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyRequestPurpose } from './propertyRequestPurpose';
import type { PropertyRequestDirection } from './propertyRequestDirection';
import type { PropertyRequestBalconyDirection } from './propertyRequestBalconyDirection';
import type { PropertyRequestStatus } from './propertyRequestStatus';
import type { UploadConfirmRequest } from './uploadConfirmRequest';

export interface PropertyRequest {
  /** @minLength 1 */
  title: string;
  purpose: PropertyRequestPurpose;
  typeId: number;
  price: number;
  lineAddress?: string;
  provinceId: number;
  wardId: number;
  landArea?: number;
  floorArea?: number;
  floors?: number;
  floorNumber?: number;
  bedrooms?: number;
  bathrooms?: number;
  direction?: PropertyRequestDirection;
  description?: string;
  entranceRoadWidth?: number;
  balconyDirection?: PropertyRequestBalconyDirection;
  hasMezzanine?: boolean;
  hasBasement?: boolean;
  hasElevator?: boolean;
  interior?: string;
  status: PropertyRequestStatus;
  medias?: UploadConfirmRequest[];
}
