/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PropertyRequestBalconyDirection = typeof PropertyRequestBalconyDirection[keyof typeof PropertyRequestBalconyDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyRequestBalconyDirection = {
  NORTH: 'NORTH',
  SOUTH: 'SOUTH',
  EAST: 'EAST',
  WEST: 'WEST',
  NORTHEAST: 'NORTHEAST',
  NORTHWEST: 'NORTHWEST',
  SOUTHEAST: 'SOUTHEAST',
  SOUTHWEST: 'SOUTHWEST',
} as const;
