/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PropertyRequestPurpose = typeof PropertyRequestPurpose[keyof typeof PropertyRequestPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyRequestPurpose = {
  FOR_SALE: 'FOR_SALE',
  FOR_RENT: 'FOR_RENT',
} as const;
