/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyResponsePurpose } from './propertyResponsePurpose';
import type { PropertyTypeResponse } from './propertyTypeResponse';
import type { WardResponse } from './wardResponse';
import type { PropertyResponseDirection } from './propertyResponseDirection';
import type { PropertyResponseBalconyDirection } from './propertyResponseBalconyDirection';
import type { PropertyResponseStatus } from './propertyResponseStatus';
import type { Location } from './location';
import type { FileResponse } from './fileResponse';

export interface PropertyResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  title?: string;
  purpose?: PropertyResponsePurpose;
  type?: PropertyTypeResponse;
  price?: number;
  lineAddress?: string;
  ward?: WardResponse;
  landArea?: number;
  floorArea?: number;
  floors?: number;
  floorNumber?: number;
  bedrooms?: number;
  bathrooms?: number;
  direction?: PropertyResponseDirection;
  description?: string;
  entranceRoadWidth?: number;
  balconyDirection?: PropertyResponseBalconyDirection;
  hasMezzanine?: boolean;
  hasBasement?: boolean;
  hasElevator?: boolean;
  status?: PropertyResponseStatus;
  interior?: string;
  location?: Location;
  documents?: FileResponse[];
  thumbnail?: FileResponse;
  galleries?: FileResponse[];
}
