/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PropertyResponseStatus = typeof PropertyResponseStatus[keyof typeof PropertyResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyResponseStatus = {
  AVAILABLE: 'AVAILABLE',
  RENTED: 'RENTED',
  SOLD: 'SOLD',
  MAINTENANCE: 'MAINTENANCE',
  UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
  OFF_MARKET: 'OFF_MARKET',
} as const;
