/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PropertyRequestPurpose } from './propertyRequestPurpose';
import type { PropertyRequestDirection } from './propertyRequestDirection';
import type { PropertyRequestBalconyDirection } from './propertyRequestBalconyDirection';
import type { PropertyRequestStatus } from './propertyRequestStatus';
import type { Location } from './location';

export interface PropertyRequest {
  /** @minLength 1 */
  title: string;
  purpose: PropertyRequestPurpose;
  typeId: number;
  price: number;
  lineAddress?: string;
  provinceId: number;
  wardId: number;
  landArea?: number;
  floorArea?: number;
  floors?: number;
  floorNumber?: number;
  bedrooms?: number;
  bathrooms?: number;
  direction?: PropertyRequestDirection;
  description?: string;
  /** @minimum 0 */
  entranceRoadWidth?: number;
  balconyDirection?: PropertyRequestBalconyDirection;
  hasMezzanine?: boolean;
  hasBasement?: boolean;
  hasElevator?: boolean;
  interior?: string;
  status: PropertyRequestStatus;
  location?: Location;
  documentIds?: number[];
  thumbnailId: number;
  galleryIds?: number[];
}
