/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PropertyResponsePurpose = typeof PropertyResponsePurpose[keyof typeof PropertyResponsePurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyResponsePurpose = {
  FOR_SALE: 'FOR_SALE',
  FOR_RENT: 'FOR_RENT',
} as const;
