/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProvinceRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  phoneCode: string;
  /** @minLength 1 */
  codeName: string;
  /** @minLength 1 */
  divisionType: string;
}
