/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ResetPasswordRequest {
  /** @minLength 1 */
  verificationCode: string;
  /** @minLength 1 */
  newPassword: string;
}
