/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RoleRequest {
  /** @minLength 1 */
  name: string;
  description?: string;
  permissionIds?: number[];
}
