/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RoleRequest {
  /** @minLength 1 */
  name: string;
  description?: string;
  canManage?: boolean;
  permissionIds?: number[];
  accessibleModules?: string[];
  default?: boolean;
}
