/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SendOtpResponseChannel = typeof SendOtpResponseChannel[keyof typeof SendOtpResponseChannel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendOtpResponseChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;
