/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SendOtpResponseChannel } from './sendOtpResponseChannel';

export interface SendOtpResponse {
  maskedDestination?: string;
  resendAfter?: number;
  expiresIn?: number;
  channel?: SendOtpResponseChannel;
}
