/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SendOtpRequestPurpose } from './sendOtpRequestPurpose';

export interface SendOtpRequest {
  /** @minLength 1 */
  destination: string;
  purpose: SendOtpRequestPurpose;
}
