/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountMetric } from './countMetric';

export interface StatisticResponse {
  totalProperties?: CountMetric;
  totalUsers?: CountMetric;
  pendingConversations?: CountMetric;
}
