/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SummarySupportResponseType } from './summarySupportResponseType';
import type { SummarySupportResponseSeverity } from './summarySupportResponseSeverity';
import type { SummarySupportResponseStatus } from './summarySupportResponseStatus';

export interface SummarySupportResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  title?: string;
  type?: SummarySupportResponseType;
  severity?: SummarySupportResponseSeverity;
  status?: SummarySupportResponseStatus;
}
