/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SupportResponseSeverity = typeof SupportResponseSeverity[keyof typeof SupportResponseSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportResponseSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;
