/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SupportResponseType } from './supportResponseType';
import type { SupportResponseSeverity } from './supportResponseSeverity';
import type { SupportResponseStatus } from './supportResponseStatus';
import type { FileResponse } from './fileResponse';

export interface SupportResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  title?: string;
  description?: string;
  type?: SupportResponseType;
  severity?: SupportResponseSeverity;
  userId?: number;
  userEmail?: string;
  userName?: string;
  status?: SupportResponseStatus;
  reply?: string;
  attachments?: FileResponse[];
}
