/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ContentBlockRequest } from './contentBlockRequest';

export interface UploadCarouselRequest {
  contentBlocks?: ContentBlockRequest[];
}
