/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UploadSignatureResponse {
  signature?: string;
  timestamp?: string;
  apiKey?: string;
  cloudName?: string;
  publicId?: string;
  folder?: string;
  tags?: string[];
}
