/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadConfirmRequestPurpose } from './uploadConfirmRequestPurpose';

export interface UploadConfirmRequest {
  /** @minLength 1 */
  publicId: string;
  version: number;
  /** @minLength 1 */
  signature: string;
  /** @minLength 1 */
  secureUrl: string;
  width: number;
  height: number;
  /** @minLength 1 */
  format: string;
  /** @minLength 1 */
  resourceType: string;
  bytes: number;
  purpose: UploadConfirmRequestPurpose;
}
