/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRequestStatus } from './userRequestStatus';

export interface UserRequest {
  fullName?: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  phone: string;
  password?: string;
  emailVerified?: boolean;
  phoneVerified?: boolean;
  status?: UserRequestStatus;
  roleId: number;
}
