/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseStatus } from './userResponseStatus';
import type { FileResponse } from './fileResponse';

export interface UserResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  emailVerified?: boolean;
  phoneVerified?: boolean;
  status?: UserResponseStatus;
  roleId?: number;
  avatar?: FileResponse;
}
