/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserResponseStatus = typeof UserResponseStatus[keyof typeof UserResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseStatus = {
  UNVERIFIED: 'UNVERIFIED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCKED: 'BLOCKED',
} as const;
