/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VerifyOtpRequestPurpose = typeof VerifyOtpRequestPurpose[keyof typeof VerifyOtpRequestPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyOtpRequestPurpose = {
  REGISTRATION: 'REGISTRATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
} as const;
