/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VerifyOtpResponsePurpose = typeof VerifyOtpResponsePurpose[keyof typeof VerifyOtpResponsePurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyOtpResponsePurpose = {
  REGISTRATION: 'REGISTRATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
} as const;
