/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VerifyOtpResponsePurpose } from './verifyOtpResponsePurpose';

export interface VerifyOtpResponse {
  verificationToken?: string;
  purpose?: VerifyOtpResponsePurpose;
}
