/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VerifyOtpRequestPurpose } from './verifyOtpRequestPurpose';

export interface VerifyOtpRequest {
  /** @minLength 1 */
  destination: string;
  /** @minLength 1 */
  otp: string;
  purpose?: VerifyOtpRequestPurpose;
}
