/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProvinceResponse } from './provinceResponse';

export interface WardResponse {
  id?: number;
  version?: number;
  createdBy?: number;
  updatedBy?: number;
  createdAt?: string;
  updatedAt?: string;
  name?: string;
  code?: string;
  type?: string;
  province?: ProvinceResponse;
}
