/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface WardRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  type: string;
  provinceId: number;
}
