/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WishRequestType = typeof WishRequestType[keyof typeof WishRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WishRequestType = {
  PROPERTY: 'PROPERTY',
} as const;
