/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WishRequestType } from './wishRequestType';

export interface WishRequest {
  identifier: number;
  type: WishRequestType;
}
