/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WishResponseType = typeof WishResponseType[keyof typeof WishResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WishResponseType = {
  PROPERTY: 'PROPERTY',
} as const;
