ALTER TABLE provinces ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE wards ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE property_types ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
