/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseMessageResponse,
  ApiResponseVoid,
  GetMessagesByConversationIdForManagerParams,
  GetMessagesByConversationIdParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getMessagesByConversationId = (
    conversationId: number,
    params?: GetMessagesByConversationIdParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseMessageResponse>(
      {url: `/chat/conversations/${conversationId}/messages`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMessagesByConversationIdQueryKey = (conversationId?: number,
    params?: GetMessagesByConversationIdParams,) => {
    return [
    `/chat/conversations/${conversationId}/messages`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMessagesByConversationIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesByConversationId>>, TError = ErrorType<unknown>>(conversationId: number,
    params?: GetMessagesByConversationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesByConversationIdQueryKey(conversationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesByConversationId>>> = ({ signal }) => getMessagesByConversationId(conversationId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(conversationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesByConversationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesByConversationId>>>
export type GetMessagesByConversationIdQueryError = ErrorType<unknown>


export function useGetMessagesByConversationId<TData = Awaited<ReturnType<typeof getMessagesByConversationId>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params: undefined |  GetMessagesByConversationIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByConversationId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByConversationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByConversationId<TData = Awaited<ReturnType<typeof getMessagesByConversationId>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByConversationId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByConversationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByConversationId<TData = Awaited<ReturnType<typeof getMessagesByConversationId>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMessagesByConversationId<TData = Awaited<ReturnType<typeof getMessagesByConversationId>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationId>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesByConversationIdQueryOptions(conversationId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMessagesByConversationIdForManager = (
    conversationId: number,
    params?: GetMessagesByConversationIdForManagerParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseMessageResponse>(
      {url: `/chat/conversations/${conversationId}/messages/manager`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMessagesByConversationIdForManagerQueryKey = (conversationId?: number,
    params?: GetMessagesByConversationIdForManagerParams,) => {
    return [
    `/chat/conversations/${conversationId}/messages/manager`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMessagesByConversationIdForManagerQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError = ErrorType<unknown>>(conversationId: number,
    params?: GetMessagesByConversationIdForManagerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesByConversationIdForManagerQueryKey(conversationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>> = ({ signal }) => getMessagesByConversationIdForManager(conversationId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(conversationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesByConversationIdForManagerQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>>
export type GetMessagesByConversationIdForManagerQueryError = ErrorType<unknown>


export function useGetMessagesByConversationIdForManager<TData = Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params: undefined |  GetMessagesByConversationIdForManagerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByConversationIdForManager<TData = Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdForManagerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByConversationIdForManager<TData = Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdForManagerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMessagesByConversationIdForManager<TData = Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError = ErrorType<unknown>>(
 conversationId: number,
    params?: GetMessagesByConversationIdForManagerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByConversationIdForManager>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesByConversationIdForManagerQueryOptions(conversationId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteMessageById = (
    messageId: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/chat/messages/${messageId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteMessageByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMessageById>>, TError,{messageId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMessageById>>, TError,{messageId: number}, TContext> => {

const mutationKey = ['deleteMessageById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMessageById>>, {messageId: number}> = (props) => {
          const {messageId} = props ?? {};

          return  deleteMessageById(messageId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMessageByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMessageById>>>
    
    export type DeleteMessageByIdMutationError = ErrorType<unknown>

    export const useDeleteMessageById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMessageById>>, TError,{messageId: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMessageById>>,
        TError,
        {messageId: number},
        TContext
      > => {

      const mutationOptions = getDeleteMessageByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    