/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const getMessagesByConversationIdParams = zod.object({
  "conversationId": zod.number()
})

export const getMessagesByConversationIdQueryPageDefault = 0;
export const getMessagesByConversationIdQueryPageMin = 0;

export const getMessagesByConversationIdQuerySizeDefault = 20;



export const getMessagesByConversationIdQueryParams = zod.object({
  "page": zod.number().min(getMessagesByConversationIdQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(getMessagesByConversationIdQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteMessageByIdParams = zod.object({
  "messageId": zod.number()
})

