/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findRoleByIdParams = zod.object({
  "id": zod.number()
})

export const updateRoleParams = zod.object({
  "id": zod.number()
})




export const updateRoleBody = zod.object({
  "name": zod.string().min(1),
  "description": zod.string().optional(),
  "canManage": zod.boolean().optional(),
  "permissionIds": zod.array(zod.number()).optional(),
  "accessibleModules": zod.array(zod.string()).optional(),
  "default": zod.boolean().optional()
})

export const deleteRoleByIdParams = zod.object({
  "id": zod.number()
})




export const createRoleBody = zod.object({
  "name": zod.string().min(1),
  "description": zod.string().optional(),
  "canManage": zod.boolean().optional(),
  "permissionIds": zod.array(zod.number()).optional(),
  "accessibleModules": zod.array(zod.string()).optional(),
  "default": zod.boolean().optional()
})

export const findAllRoleQueryPageDefault = 0;
export const findAllRoleQueryPageMin = 0;

export const findAllRoleQuerySizeDefault = 20;

export const findAllRoleQueryAllDefault = false;

export const findAllRoleQueryParams = zod.object({
  "page": zod.number().min(findAllRoleQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllRoleQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkRoleQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

