/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseRoleResponse,
  ApiResponseRoleResponse,
  ApiResponseVoid,
  DeleteBulkRoleParams,
  FindAllRoleParams,
  RoleRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findRoleById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseRoleResponse>(
      {url: `/roles/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindRoleByIdQueryKey = (id?: number,) => {
    return [
    `/roles/${id}`
    ] as const;
    }

    
export const getFindRoleByIdQueryOptions = <TData = Awaited<ReturnType<typeof findRoleById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindRoleByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findRoleById>>> = ({ signal }) => findRoleById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindRoleByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findRoleById>>>
export type FindRoleByIdQueryError = ErrorType<unknown>


export function useFindRoleById<TData = Awaited<ReturnType<typeof findRoleById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findRoleById>>,
          TError,
          Awaited<ReturnType<typeof findRoleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindRoleById<TData = Awaited<ReturnType<typeof findRoleById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findRoleById>>,
          TError,
          Awaited<ReturnType<typeof findRoleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindRoleById<TData = Awaited<ReturnType<typeof findRoleById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindRoleById<TData = Awaited<ReturnType<typeof findRoleById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRoleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindRoleByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateRole = (
    id: number,
    roleRequest: BodyType<RoleRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseRoleResponse>(
      {url: `/roles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roleRequest
    },
      options);
    }
  


export const getUpdateRoleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: BodyType<RoleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: BodyType<RoleRequest>}, TContext> => {

const mutationKey = ['updateRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRole>>, {id: number;data: BodyType<RoleRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRole(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateRole>>>
    export type UpdateRoleMutationBody = BodyType<RoleRequest>
    export type UpdateRoleMutationError = ErrorType<unknown>

    export const useUpdateRole = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: BodyType<RoleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRole>>,
        TError,
        {id: number;data: BodyType<RoleRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteRoleById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/roles/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRoleByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoleById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRoleById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteRoleById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRoleById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteRoleById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRoleByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoleById>>>
    
    export type DeleteRoleByIdMutationError = ErrorType<unknown>

    export const useDeleteRoleById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoleById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRoleById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteRoleByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createRole = (
    roleRequest: BodyType<RoleRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseRoleResponse>(
      {url: `/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roleRequest, signal
    },
      options);
    }
  


export const getCreateRoleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: BodyType<RoleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: BodyType<RoleRequest>}, TContext> => {

const mutationKey = ['createRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRole>>, {data: BodyType<RoleRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createRole(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof createRole>>>
    export type CreateRoleMutationBody = BodyType<RoleRequest>
    export type CreateRoleMutationError = ErrorType<unknown>

    export const useCreateRole = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: BodyType<RoleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRole>>,
        TError,
        {data: BodyType<RoleRequest>},
        TContext
      > => {

      const mutationOptions = getCreateRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllRole = (
    params?: FindAllRoleParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseRoleResponse>(
      {url: `/roles/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllRoleQueryKey = (params?: FindAllRoleParams,) => {
    return [
    `/roles/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllRoleQueryOptions = <TData = Awaited<ReturnType<typeof findAllRole>>, TError = ErrorType<unknown>>(params?: FindAllRoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllRoleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllRole>>> = ({ signal }) => findAllRole(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllRoleQueryResult = NonNullable<Awaited<ReturnType<typeof findAllRole>>>
export type FindAllRoleQueryError = ErrorType<unknown>


export function useFindAllRole<TData = Awaited<ReturnType<typeof findAllRole>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllRoleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllRole>>,
          TError,
          Awaited<ReturnType<typeof findAllRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllRole<TData = Awaited<ReturnType<typeof findAllRole>>, TError = ErrorType<unknown>>(
 params?: FindAllRoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllRole>>,
          TError,
          Awaited<ReturnType<typeof findAllRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllRole<TData = Awaited<ReturnType<typeof findAllRole>>, TError = ErrorType<unknown>>(
 params?: FindAllRoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllRole<TData = Awaited<ReturnType<typeof findAllRole>>, TError = ErrorType<unknown>>(
 params?: FindAllRoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllRole>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllRoleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkRole = (
    params: DeleteBulkRoleParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/roles/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkRoleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkRole>>, TError,{params: DeleteBulkRoleParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkRole>>, TError,{params: DeleteBulkRoleParams}, TContext> => {

const mutationKey = ['deleteBulkRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkRole>>, {params: DeleteBulkRoleParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkRole(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkRoleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkRole>>>
    
    export type DeleteBulkRoleMutationError = ErrorType<unknown>

    export const useDeleteBulkRole = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkRole>>, TError,{params: DeleteBulkRoleParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkRole>>,
        TError,
        {params: DeleteBulkRoleParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    