/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseListContentBlockResponse,
  ApiResponseVoid,
  UploadCarouselRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const uploadCarousel = (
    uploadCarouselRequest: BodyType<UploadCarouselRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/content-blocks/upload-carousel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadCarouselRequest, signal
    },
      options);
    }
  


export const getUploadCarouselMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCarousel>>, TError,{data: BodyType<UploadCarouselRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadCarousel>>, TError,{data: BodyType<UploadCarouselRequest>}, TContext> => {

const mutationKey = ['uploadCarousel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadCarousel>>, {data: BodyType<UploadCarouselRequest>}> = (props) => {
          const {data} = props ?? {};

          return  uploadCarousel(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadCarouselMutationResult = NonNullable<Awaited<ReturnType<typeof uploadCarousel>>>
    export type UploadCarouselMutationBody = BodyType<UploadCarouselRequest>
    export type UploadCarouselMutationError = ErrorType<unknown>

    export const useUploadCarousel = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCarousel>>, TError,{data: BodyType<UploadCarouselRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadCarousel>>,
        TError,
        {data: BodyType<UploadCarouselRequest>},
        TContext
      > => {

      const mutationOptions = getUploadCarouselMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCarousels = (
    
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseListContentBlockResponse>(
      {url: `/content-blocks/carousels`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCarouselsQueryKey = () => {
    return [
    `/content-blocks/carousels`
    ] as const;
    }

    
export const getGetCarouselsQueryOptions = <TData = Awaited<ReturnType<typeof getCarousels>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCarouselsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarousels>>> = ({ signal }) => getCarousels(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCarouselsQueryResult = NonNullable<Awaited<ReturnType<typeof getCarousels>>>
export type GetCarouselsQueryError = ErrorType<unknown>


export function useGetCarousels<TData = Awaited<ReturnType<typeof getCarousels>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarousels>>,
          TError,
          Awaited<ReturnType<typeof getCarousels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCarousels<TData = Awaited<ReturnType<typeof getCarousels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarousels>>,
          TError,
          Awaited<ReturnType<typeof getCarousels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCarousels<TData = Awaited<ReturnType<typeof getCarousels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCarousels<TData = Awaited<ReturnType<typeof getCarousels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCarousels>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCarouselsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




