/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const getStatisticsQueryGranularityDefault = "DAILY";

export const getStatisticsQueryParams = zod.object({
  "startDate": zod.iso.datetime({}).optional(),
  "endDate": zod.iso.datetime({}).optional(),
  "granularity": zod.enum(['DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']).default(getStatisticsQueryGranularityDefault)
})

