/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseStatisticResponse,
  GetStatisticsParams
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getStatistics = (
    params?: GetStatisticsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseStatisticResponse>(
      {url: `/statistics`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetStatisticsQueryKey = (params?: GetStatisticsParams,) => {
    return [
    `/statistics`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getStatistics>>, TError = ErrorType<unknown>>(params?: GetStatisticsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatistics>>> = ({ signal }) => getStatistics(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getStatistics>>>
export type GetStatisticsQueryError = ErrorType<unknown>


export function useGetStatistics<TData = Awaited<ReturnType<typeof getStatistics>>, TError = ErrorType<unknown>>(
 params: undefined |  GetStatisticsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistics>>,
          TError,
          Awaited<ReturnType<typeof getStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatistics<TData = Awaited<ReturnType<typeof getStatistics>>, TError = ErrorType<unknown>>(
 params?: GetStatisticsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistics>>,
          TError,
          Awaited<ReturnType<typeof getStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatistics<TData = Awaited<ReturnType<typeof getStatistics>>, TError = ErrorType<unknown>>(
 params?: GetStatisticsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStatistics<TData = Awaited<ReturnType<typeof getStatistics>>, TError = ErrorType<unknown>>(
 params?: GetStatisticsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistics>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




