/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * Nếu sử dụng swagger thì sẽ không được do bị chặn bởi CORS. Vui lòng click vào link kế bên để đăng nhập bằng Google.[/oauth2/authorize/google](/oauth2/authorize/google)
 * @summary Endpoint giúp đăng nhập bằng OAuth2. Hiện tại hỗ trợ Google
 */
export const redirectToProviderParams = zod.object({
  "provider": zod.string()
})

