/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


export const findWardByIdParams = zod.object({
  "id": zod.number()
})

export const updateWardParams = zod.object({
  "id": zod.number()
})

export const updateWardBody = zod.object({
  "name": zod.string().min(1),
  "codeName": zod.string().min(1),
  "provinceId": zod.number()
})

export const deleteWardByIdParams = zod.object({
  "id": zod.number()
})

export const createWardBody = zod.object({
  "name": zod.string().min(1),
  "codeName": zod.string().min(1),
  "provinceId": zod.number()
})

export const findAllWardQueryPageDefault = 0;
export const findAllWardQueryPageMin = 0;
export const findAllWardQuerySizeDefault = 20;

export const findAllWardQueryParams = zod.object({
  "page": zod.number().min(findAllWardQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllWardQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional()
})

export const deleteBulkWardQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

