/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseWardResponse,
  ApiResponseVoid,
  ApiResponseWardResponse,
  DeleteBulkWardParams,
  FindAllWardParams,
  WardRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findWardById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWardResponse>(
      {url: `/wards/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindWardByIdQueryKey = (id?: number,) => {
    return [
    `/wards/${id}`
    ] as const;
    }

    
export const getFindWardByIdQueryOptions = <TData = Awaited<ReturnType<typeof findWardById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindWardByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findWardById>>> = ({ signal }) => findWardById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindWardByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findWardById>>>
export type FindWardByIdQueryError = ErrorType<unknown>


export function useFindWardById<TData = Awaited<ReturnType<typeof findWardById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findWardById>>,
          TError,
          Awaited<ReturnType<typeof findWardById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindWardById<TData = Awaited<ReturnType<typeof findWardById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findWardById>>,
          TError,
          Awaited<ReturnType<typeof findWardById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindWardById<TData = Awaited<ReturnType<typeof findWardById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindWardById<TData = Awaited<ReturnType<typeof findWardById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWardById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindWardByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateWard = (
    id: number,
    wardRequest: BodyType<WardRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseWardResponse>(
      {url: `/wards/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: wardRequest
    },
      options);
    }
  


export const getUpdateWardMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: number;data: BodyType<WardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: number;data: BodyType<WardRequest>}, TContext> => {

const mutationKey = ['updateWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWard>>, {id: number;data: BodyType<WardRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateWard(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWardMutationResult = NonNullable<Awaited<ReturnType<typeof updateWard>>>
    export type UpdateWardMutationBody = BodyType<WardRequest>
    export type UpdateWardMutationError = ErrorType<unknown>

    export const useUpdateWard = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: number;data: BodyType<WardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWard>>,
        TError,
        {id: number;data: BodyType<WardRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateWardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteWardById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/wards/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWardByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWardById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWardById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteWardById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWardById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteWardById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWardByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWardById>>>
    
    export type DeleteWardByIdMutationError = ErrorType<unknown>

    export const useDeleteWardById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWardById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWardById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteWardByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createWard = (
    wardRequest: BodyType<WardRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWardResponse>(
      {url: `/wards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wardRequest, signal
    },
      options);
    }
  


export const getCreateWardMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<WardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<WardRequest>}, TContext> => {

const mutationKey = ['createWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWard>>, {data: BodyType<WardRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createWard(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWardMutationResult = NonNullable<Awaited<ReturnType<typeof createWard>>>
    export type CreateWardMutationBody = BodyType<WardRequest>
    export type CreateWardMutationError = ErrorType<unknown>

    export const useCreateWard = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<WardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWard>>,
        TError,
        {data: BodyType<WardRequest>},
        TContext
      > => {

      const mutationOptions = getCreateWardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllWard = (
    params?: FindAllWardParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseWardResponse>(
      {url: `/wards/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllWardQueryKey = (params?: FindAllWardParams,) => {
    return [
    `/wards/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllWardQueryOptions = <TData = Awaited<ReturnType<typeof findAllWard>>, TError = ErrorType<unknown>>(params?: FindAllWardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllWardQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllWard>>> = ({ signal }) => findAllWard(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllWardQueryResult = NonNullable<Awaited<ReturnType<typeof findAllWard>>>
export type FindAllWardQueryError = ErrorType<unknown>


export function useFindAllWard<TData = Awaited<ReturnType<typeof findAllWard>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllWardParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllWard>>,
          TError,
          Awaited<ReturnType<typeof findAllWard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllWard<TData = Awaited<ReturnType<typeof findAllWard>>, TError = ErrorType<unknown>>(
 params?: FindAllWardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllWard>>,
          TError,
          Awaited<ReturnType<typeof findAllWard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllWard<TData = Awaited<ReturnType<typeof findAllWard>>, TError = ErrorType<unknown>>(
 params?: FindAllWardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllWard<TData = Awaited<ReturnType<typeof findAllWard>>, TError = ErrorType<unknown>>(
 params?: FindAllWardParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWard>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllWardQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkWard = (
    params: DeleteBulkWardParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/wards/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkWardMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWard>>, TError,{params: DeleteBulkWardParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWard>>, TError,{params: DeleteBulkWardParams}, TContext> => {

const mutationKey = ['deleteBulkWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkWard>>, {params: DeleteBulkWardParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkWard(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkWardMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkWard>>>
    
    export type DeleteBulkWardMutationError = ErrorType<unknown>

    export const useDeleteBulkWard = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWard>>, TError,{params: DeleteBulkWardParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkWard>>,
        TError,
        {params: DeleteBulkWardParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkWardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    