/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseWishResponse,
  ApiResponseVoid,
  ApiResponseWishResponse,
  DeleteBulkWishParams,
  FindAllWishParams,
  WishRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findWishById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWishResponse>(
      {url: `/wishs/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindWishByIdQueryKey = (id?: number,) => {
    return [
    `/wishs/${id}`
    ] as const;
    }

    
export const getFindWishByIdQueryOptions = <TData = Awaited<ReturnType<typeof findWishById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindWishByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findWishById>>> = ({ signal }) => findWishById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindWishByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findWishById>>>
export type FindWishByIdQueryError = ErrorType<unknown>


export function useFindWishById<TData = Awaited<ReturnType<typeof findWishById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findWishById>>,
          TError,
          Awaited<ReturnType<typeof findWishById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindWishById<TData = Awaited<ReturnType<typeof findWishById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findWishById>>,
          TError,
          Awaited<ReturnType<typeof findWishById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindWishById<TData = Awaited<ReturnType<typeof findWishById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindWishById<TData = Awaited<ReturnType<typeof findWishById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findWishById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindWishByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateWish = (
    id: number,
    wishRequest: BodyType<WishRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseWishResponse>(
      {url: `/wishs/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: wishRequest
    },
      options);
    }
  


export const getUpdateWishMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWish>>, TError,{id: number;data: BodyType<WishRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWish>>, TError,{id: number;data: BodyType<WishRequest>}, TContext> => {

const mutationKey = ['updateWish'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWish>>, {id: number;data: BodyType<WishRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateWish(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWishMutationResult = NonNullable<Awaited<ReturnType<typeof updateWish>>>
    export type UpdateWishMutationBody = BodyType<WishRequest>
    export type UpdateWishMutationError = ErrorType<unknown>

    export const useUpdateWish = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWish>>, TError,{id: number;data: BodyType<WishRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWish>>,
        TError,
        {id: number;data: BodyType<WishRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateWishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteWishById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/wishs/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWishByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWishById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWishById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteWishById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWishById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteWishById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWishByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWishById>>>
    
    export type DeleteWishByIdMutationError = ErrorType<unknown>

    export const useDeleteWishById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWishById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWishById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteWishByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createWish = (
    wishRequest: BodyType<WishRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWishResponse>(
      {url: `/wishs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wishRequest, signal
    },
      options);
    }
  


export const getCreateWishMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWish>>, TError,{data: BodyType<WishRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createWish>>, TError,{data: BodyType<WishRequest>}, TContext> => {

const mutationKey = ['createWish'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWish>>, {data: BodyType<WishRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createWish(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWishMutationResult = NonNullable<Awaited<ReturnType<typeof createWish>>>
    export type CreateWishMutationBody = BodyType<WishRequest>
    export type CreateWishMutationError = ErrorType<unknown>

    export const useCreateWish = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWish>>, TError,{data: BodyType<WishRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWish>>,
        TError,
        {data: BodyType<WishRequest>},
        TContext
      > => {

      const mutationOptions = getCreateWishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllWish = (
    params?: FindAllWishParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseWishResponse>(
      {url: `/wishs/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllWishQueryKey = (params?: FindAllWishParams,) => {
    return [
    `/wishs/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllWishQueryOptions = <TData = Awaited<ReturnType<typeof findAllWish>>, TError = ErrorType<unknown>>(params?: FindAllWishParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllWishQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllWish>>> = ({ signal }) => findAllWish(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllWishQueryResult = NonNullable<Awaited<ReturnType<typeof findAllWish>>>
export type FindAllWishQueryError = ErrorType<unknown>


export function useFindAllWish<TData = Awaited<ReturnType<typeof findAllWish>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllWishParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllWish>>,
          TError,
          Awaited<ReturnType<typeof findAllWish>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllWish<TData = Awaited<ReturnType<typeof findAllWish>>, TError = ErrorType<unknown>>(
 params?: FindAllWishParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllWish>>,
          TError,
          Awaited<ReturnType<typeof findAllWish>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllWish<TData = Awaited<ReturnType<typeof findAllWish>>, TError = ErrorType<unknown>>(
 params?: FindAllWishParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllWish<TData = Awaited<ReturnType<typeof findAllWish>>, TError = ErrorType<unknown>>(
 params?: FindAllWishParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllWish>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllWishQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkWish = (
    params: DeleteBulkWishParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/wishs/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkWishMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWish>>, TError,{params: DeleteBulkWishParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWish>>, TError,{params: DeleteBulkWishParams}, TContext> => {

const mutationKey = ['deleteBulkWish'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkWish>>, {params: DeleteBulkWishParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkWish(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkWishMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkWish>>>
    
    export type DeleteBulkWishMutationError = ErrorType<unknown>

    export const useDeleteBulkWish = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkWish>>, TError,{params: DeleteBulkWishParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkWish>>,
        TError,
        {params: DeleteBulkWishParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkWishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    