/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findWishByIdParams = zod.object({
  "id": zod.number()
})

export const updateWishParams = zod.object({
  "id": zod.number()
})

export const updateWishBody = zod.object({
  "identifier": zod.number(),
  "type": zod.enum(['PROPERTY'])
})

export const deleteWishByIdParams = zod.object({
  "id": zod.number()
})

export const createWishBody = zod.object({
  "identifier": zod.number(),
  "type": zod.enum(['PROPERTY'])
})

export const findAllWishQueryPageDefault = 0;
export const findAllWishQueryPageMin = 0;

export const findAllWishQuerySizeDefault = 20;

export const findAllWishQueryAllDefault = false;

export const findAllWishQueryParams = zod.object({
  "page": zod.number().min(findAllWishQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllWishQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkWishQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

