/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


export const findPropertyByIdParams = zod.object({
  "id": zod.number()
})

export const updatePropertyParams = zod.object({
  "id": zod.number()
})

export const updatePropertyBody = zod.object({
  "title": zod.string().min(1),
  "purpose": zod.enum(['FOR_SALE', 'FOR_RENT']),
  "typeId": zod.number(),
  "price": zod.number(),
  "lineAddress": zod.string().min(1),
  "provinceId": zod.number(),
  "wardId": zod.number(),
  "landArea": zod.number().optional(),
  "floorArea": zod.number().optional(),
  "floors": zod.number().optional(),
  "floorNumber": zod.number().optional(),
  "bedrooms": zod.number().optional(),
  "bathrooms": zod.number().optional(),
  "direction": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "description": zod.string().optional(),
  "entranceRoadWidth": zod.number().optional(),
  "balconyDirection": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "hasMezzanine": zod.boolean().optional(),
  "hasBasement": zod.boolean().optional(),
  "hasElevator": zod.boolean().optional(),
  "interior": zod.string().optional(),
  "status": zod.enum(['AVAILABLE', 'RENTED', 'SOLD', 'MAINTENANCE', 'UNDER_CONSTRUCTION', 'OFF_MARKET']),
  "medias": zod.array(zod.object({
  "publicId": zod.string().min(1),
  "version": zod.number(),
  "signature": zod.string().min(1),
  "secureUrl": zod.string().min(1),
  "width": zod.number(),
  "height": zod.number(),
  "format": zod.string().min(1),
  "resourceType": zod.string().min(1),
  "bytes": zod.number(),
  "purpose": zod.enum(['AVATAR', 'THUMBNAIL', 'BANNER', 'VIDEO', 'GALLERY'])
})).optional()
})

export const deletePropertyByIdParams = zod.object({
  "id": zod.number()
})

export const createPropertyBody = zod.object({
  "title": zod.string().min(1),
  "purpose": zod.enum(['FOR_SALE', 'FOR_RENT']),
  "typeId": zod.number(),
  "price": zod.number(),
  "lineAddress": zod.string().min(1),
  "provinceId": zod.number(),
  "wardId": zod.number(),
  "landArea": zod.number().optional(),
  "floorArea": zod.number().optional(),
  "floors": zod.number().optional(),
  "floorNumber": zod.number().optional(),
  "bedrooms": zod.number().optional(),
  "bathrooms": zod.number().optional(),
  "direction": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "description": zod.string().optional(),
  "entranceRoadWidth": zod.number().optional(),
  "balconyDirection": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "hasMezzanine": zod.boolean().optional(),
  "hasBasement": zod.boolean().optional(),
  "hasElevator": zod.boolean().optional(),
  "interior": zod.string().optional(),
  "status": zod.enum(['AVAILABLE', 'RENTED', 'SOLD', 'MAINTENANCE', 'UNDER_CONSTRUCTION', 'OFF_MARKET']),
  "medias": zod.array(zod.object({
  "publicId": zod.string().min(1),
  "version": zod.number(),
  "signature": zod.string().min(1),
  "secureUrl": zod.string().min(1),
  "width": zod.number(),
  "height": zod.number(),
  "format": zod.string().min(1),
  "resourceType": zod.string().min(1),
  "bytes": zod.number(),
  "purpose": zod.enum(['AVATAR', 'THUMBNAIL', 'BANNER', 'VIDEO', 'GALLERY'])
})).optional()
})

export const findAllPropertyQueryPageDefault = 0;
export const findAllPropertyQueryPageMin = 0;
export const findAllPropertyQuerySizeDefault = 20;export const findAllPropertyQueryAllDefault = false;

export const findAllPropertyQueryParams = zod.object({
  "page": zod.number().min(findAllPropertyQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllPropertyQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkPropertyQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

