/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponsePropertyResponse,
  ApiResponsePropertyResponse,
  ApiResponseVoid,
  DeleteBulkPropertyParams,
  FindAllPropertyParams,
  PropertyRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findPropertyById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePropertyResponse>(
      {url: `/properties/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindPropertyByIdQueryKey = (id?: number,) => {
    return [
    `/properties/${id}`
    ] as const;
    }

    
export const getFindPropertyByIdQueryOptions = <TData = Awaited<ReturnType<typeof findPropertyById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindPropertyByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findPropertyById>>> = ({ signal }) => findPropertyById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindPropertyByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findPropertyById>>>
export type FindPropertyByIdQueryError = ErrorType<unknown>


export function useFindPropertyById<TData = Awaited<ReturnType<typeof findPropertyById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPropertyById>>,
          TError,
          Awaited<ReturnType<typeof findPropertyById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindPropertyById<TData = Awaited<ReturnType<typeof findPropertyById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPropertyById>>,
          TError,
          Awaited<ReturnType<typeof findPropertyById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindPropertyById<TData = Awaited<ReturnType<typeof findPropertyById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindPropertyById<TData = Awaited<ReturnType<typeof findPropertyById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPropertyById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindPropertyByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateProperty = (
    id: number,
    propertyRequest: BodyType<PropertyRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponsePropertyResponse>(
      {url: `/properties/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: propertyRequest
    },
      options);
    }
  


export const getUpdatePropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProperty>>, TError,{id: number;data: BodyType<PropertyRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProperty>>, TError,{id: number;data: BodyType<PropertyRequest>}, TContext> => {

const mutationKey = ['updateProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProperty>>, {id: number;data: BodyType<PropertyRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProperty(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePropertyMutationResult = NonNullable<Awaited<ReturnType<typeof updateProperty>>>
    export type UpdatePropertyMutationBody = BodyType<PropertyRequest>
    export type UpdatePropertyMutationError = ErrorType<unknown>

    export const useUpdateProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProperty>>, TError,{id: number;data: BodyType<PropertyRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProperty>>,
        TError,
        {id: number;data: BodyType<PropertyRequest>},
        TContext
      > => {

      const mutationOptions = getUpdatePropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePropertyById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/properties/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeletePropertyByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePropertyById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePropertyById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePropertyById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePropertyById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePropertyById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePropertyByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deletePropertyById>>>
    
    export type DeletePropertyByIdMutationError = ErrorType<unknown>

    export const useDeletePropertyById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePropertyById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePropertyById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePropertyByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createProperty = (
    propertyRequest: BodyType<PropertyRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePropertyResponse>(
      {url: `/properties`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: propertyRequest, signal
    },
      options);
    }
  


export const getCreatePropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyRequest>}, TContext> => {

const mutationKey = ['createProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProperty>>, {data: BodyType<PropertyRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createProperty(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePropertyMutationResult = NonNullable<Awaited<ReturnType<typeof createProperty>>>
    export type CreatePropertyMutationBody = BodyType<PropertyRequest>
    export type CreatePropertyMutationError = ErrorType<unknown>

    export const useCreateProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProperty>>,
        TError,
        {data: BodyType<PropertyRequest>},
        TContext
      > => {

      const mutationOptions = getCreatePropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllProperty = (
    params?: FindAllPropertyParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponsePropertyResponse>(
      {url: `/properties/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllPropertyQueryKey = (params?: FindAllPropertyParams,) => {
    return [
    `/properties/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllPropertyQueryOptions = <TData = Awaited<ReturnType<typeof findAllProperty>>, TError = ErrorType<unknown>>(params?: FindAllPropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllPropertyQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllProperty>>> = ({ signal }) => findAllProperty(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllPropertyQueryResult = NonNullable<Awaited<ReturnType<typeof findAllProperty>>>
export type FindAllPropertyQueryError = ErrorType<unknown>


export function useFindAllProperty<TData = Awaited<ReturnType<typeof findAllProperty>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllPropertyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllProperty>>,
          TError,
          Awaited<ReturnType<typeof findAllProperty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllProperty<TData = Awaited<ReturnType<typeof findAllProperty>>, TError = ErrorType<unknown>>(
 params?: FindAllPropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllProperty>>,
          TError,
          Awaited<ReturnType<typeof findAllProperty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllProperty<TData = Awaited<ReturnType<typeof findAllProperty>>, TError = ErrorType<unknown>>(
 params?: FindAllPropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllProperty<TData = Awaited<ReturnType<typeof findAllProperty>>, TError = ErrorType<unknown>>(
 params?: FindAllPropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllProperty>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllPropertyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkProperty = (
    params: DeleteBulkPropertyParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/properties/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkPropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProperty>>, TError,{params: DeleteBulkPropertyParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProperty>>, TError,{params: DeleteBulkPropertyParams}, TContext> => {

const mutationKey = ['deleteBulkProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkProperty>>, {params: DeleteBulkPropertyParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkProperty(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkProperty>>>
    
    export type DeleteBulkPropertyMutationError = ErrorType<unknown>

    export const useDeleteBulkProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkProperty>>, TError,{params: DeleteBulkPropertyParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkProperty>>,
        TError,
        {params: DeleteBulkPropertyParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkPropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    