/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findPropertyByIdParams = zod.object({
  "id": zod.number()
})

export const updatePropertyParams = zod.object({
  "id": zod.number()
})


export const updatePropertyBodyPriceMin = 0;

export const updatePropertyBodyLandAreaMin = 0;

export const updatePropertyBodyFloorAreaMin = 0;

export const updatePropertyBodyFloorsMin = 0;

export const updatePropertyBodyFloorNumberMin = 0;

export const updatePropertyBodyBedroomsMin = 0;

export const updatePropertyBodyBathroomsMin = 0;

export const updatePropertyBodyEntranceRoadWidthMin = 0;







export const updatePropertyBody = zod.object({
  "title": zod.string().min(1),
  "purpose": zod.enum(['FOR_SALE', 'FOR_RENT']),
  "typeId": zod.number(),
  "price": zod.number().min(updatePropertyBodyPriceMin),
  "lineAddress": zod.string().optional(),
  "provinceId": zod.number(),
  "wardId": zod.number(),
  "landArea": zod.number().min(updatePropertyBodyLandAreaMin).optional(),
  "floorArea": zod.number().min(updatePropertyBodyFloorAreaMin).optional(),
  "floors": zod.number().min(updatePropertyBodyFloorsMin).optional(),
  "floorNumber": zod.number().min(updatePropertyBodyFloorNumberMin).optional(),
  "bedrooms": zod.number().min(updatePropertyBodyBedroomsMin).optional(),
  "bathrooms": zod.number().min(updatePropertyBodyBathroomsMin).optional(),
  "direction": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "description": zod.string().optional(),
  "entranceRoadWidth": zod.number().min(updatePropertyBodyEntranceRoadWidthMin).optional(),
  "balconyDirection": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "hasMezzanine": zod.boolean().optional(),
  "hasBasement": zod.boolean().optional(),
  "hasElevator": zod.boolean().optional(),
  "interior": zod.string().optional(),
  "status": zod.enum(['AVAILABLE', 'RENTED', 'SOLD', 'MAINTENANCE', 'UNDER_CONSTRUCTION', 'OFF_MARKET']),
  "medias": zod.array(zod.object({
  "publicId": zod.string().min(1),
  "version": zod.number(),
  "signature": zod.string().optional(),
  "secureUrl": zod.string().min(1),
  "width": zod.number(),
  "height": zod.number(),
  "format": zod.string().min(1),
  "resourceType": zod.string().min(1),
  "bytes": zod.number(),
  "purpose": zod.enum(['AVATAR', 'THUMBNAIL', 'BANNER', 'VIDEO', 'GALLERY'])
})).optional(),
  "location": zod.object({
  "longitude": zod.number(),
  "latitude": zod.number()
}).optional()
})

export const deletePropertyByIdParams = zod.object({
  "id": zod.number()
})


export const createPropertyBodyPriceMin = 0;

export const createPropertyBodyLandAreaMin = 0;

export const createPropertyBodyFloorAreaMin = 0;

export const createPropertyBodyFloorsMin = 0;

export const createPropertyBodyFloorNumberMin = 0;

export const createPropertyBodyBedroomsMin = 0;

export const createPropertyBodyBathroomsMin = 0;

export const createPropertyBodyEntranceRoadWidthMin = 0;







export const createPropertyBody = zod.object({
  "title": zod.string().min(1),
  "purpose": zod.enum(['FOR_SALE', 'FOR_RENT']),
  "typeId": zod.number(),
  "price": zod.number().min(createPropertyBodyPriceMin),
  "lineAddress": zod.string().optional(),
  "provinceId": zod.number(),
  "wardId": zod.number(),
  "landArea": zod.number().min(createPropertyBodyLandAreaMin).optional(),
  "floorArea": zod.number().min(createPropertyBodyFloorAreaMin).optional(),
  "floors": zod.number().min(createPropertyBodyFloorsMin).optional(),
  "floorNumber": zod.number().min(createPropertyBodyFloorNumberMin).optional(),
  "bedrooms": zod.number().min(createPropertyBodyBedroomsMin).optional(),
  "bathrooms": zod.number().min(createPropertyBodyBathroomsMin).optional(),
  "direction": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "description": zod.string().optional(),
  "entranceRoadWidth": zod.number().min(createPropertyBodyEntranceRoadWidthMin).optional(),
  "balconyDirection": zod.enum(['NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']).optional(),
  "hasMezzanine": zod.boolean().optional(),
  "hasBasement": zod.boolean().optional(),
  "hasElevator": zod.boolean().optional(),
  "interior": zod.string().optional(),
  "status": zod.enum(['AVAILABLE', 'RENTED', 'SOLD', 'MAINTENANCE', 'UNDER_CONSTRUCTION', 'OFF_MARKET']),
  "medias": zod.array(zod.object({
  "publicId": zod.string().min(1),
  "version": zod.number(),
  "signature": zod.string().optional(),
  "secureUrl": zod.string().min(1),
  "width": zod.number(),
  "height": zod.number(),
  "format": zod.string().min(1),
  "resourceType": zod.string().min(1),
  "bytes": zod.number(),
  "purpose": zod.enum(['AVATAR', 'THUMBNAIL', 'BANNER', 'VIDEO', 'GALLERY'])
})).optional(),
  "location": zod.object({
  "longitude": zod.number(),
  "latitude": zod.number()
}).optional()
})

export const findPropertiesWithinRadiusQueryParams = zod.object({
  "latitude": zod.number(),
  "longitude": zod.number(),
  "radiusInMeters": zod.number()
})

export const findSimilarPropertiesParams = zod.object({
  "id": zod.number()
})

export const findSimilarPropertiesQueryLimitDefault = 5;

export const findSimilarPropertiesQueryParams = zod.object({
  "limit": zod.number().default(findSimilarPropertiesQueryLimitDefault)
})

export const findAllPropertyQueryPageDefault = 0;
export const findAllPropertyQueryPageMin = 0;

export const findAllPropertyQuerySizeDefault = 20;

export const findAllPropertyQueryAllDefault = false;

export const findAllPropertyQueryParams = zod.object({
  "page": zod.number().min(findAllPropertyQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllPropertyQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkPropertyQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

