/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AiChatRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const stream = (
    aiChatRequest: BodyType<AiChatRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<string[]>(
      {url: `/ai/chat/stream`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiChatRequest, signal
    },
      options);
    }
  


export const getStreamMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stream>>, TError,{data: BodyType<AiChatRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof stream>>, TError,{data: BodyType<AiChatRequest>}, TContext> => {

const mutationKey = ['stream'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stream>>, {data: BodyType<AiChatRequest>}> = (props) => {
          const {data} = props ?? {};

          return  stream(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StreamMutationResult = NonNullable<Awaited<ReturnType<typeof stream>>>
    export type StreamMutationBody = BodyType<AiChatRequest>
    export type StreamMutationError = ErrorType<unknown>

    export const useStream = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stream>>, TError,{data: BodyType<AiChatRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stream>>,
        TError,
        {data: BodyType<AiChatRequest>},
        TContext
      > => {

      const mutationOptions = getStreamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const query = (
    aiChatRequest: BodyType<AiChatRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<string>(
      {url: `/ai/chat/query`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiChatRequest, signal
    },
      options);
    }
  


export const getQueryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof query>>, TError,{data: BodyType<AiChatRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof query>>, TError,{data: BodyType<AiChatRequest>}, TContext> => {

const mutationKey = ['query'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof query>>, {data: BodyType<AiChatRequest>}> = (props) => {
          const {data} = props ?? {};

          return  query(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type QueryMutationResult = NonNullable<Awaited<ReturnType<typeof query>>>
    export type QueryMutationBody = BodyType<AiChatRequest>
    export type QueryMutationError = ErrorType<unknown>

    export const useQuery = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof query>>, TError,{data: BodyType<AiChatRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof query>>,
        TError,
        {data: BodyType<AiChatRequest>},
        TContext
      > => {

      const mutationOptions = getQueryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    