/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const streamBody = zod.object({
  "message": zod.string().optional(),
  "conversationId": zod.string().optional()
})

export const chatBody = zod.object({
  "message": zod.string().optional(),
  "conversationId": zod.string().optional()
})

