/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const findPermissionByIdParams = zod.object({
  "id": zod.number()
})

export const updatePermissionParams = zod.object({
  "id": zod.number()
})






export const updatePermissionBody = zod.object({
  "name": zod.string().min(1),
  "resource": zod.string().min(1),
  "urlPattern": zod.string().min(1),
  "method": zod.enum(['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'])
})

export const deletePermissionByIdParams = zod.object({
  "id": zod.number()
})






export const createPermissionBody = zod.object({
  "name": zod.string().min(1),
  "resource": zod.string().min(1),
  "urlPattern": zod.string().min(1),
  "method": zod.enum(['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'])
})

export const findAllPermissionQueryPageDefault = 0;
export const findAllPermissionQueryPageMin = 0;

export const findAllPermissionQuerySizeDefault = 20;

export const findAllPermissionQueryAllDefault = false;

export const findAllPermissionQueryParams = zod.object({
  "page": zod.number().min(findAllPermissionQueryPageMin).optional().describe('Zero-based page index (0..N)'),
  "size": zod.number().min(1).default(findAllPermissionQuerySizeDefault).describe('The size of the page to be returned'),
  "sort": zod.array(zod.string()).optional().describe('Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'),
  "filter": zod.string().optional(),
  "all": zod.boolean().optional()
})

export const deleteBulkPermissionQueryParams = zod.object({
  "ids": zod.array(zod.number())
})

