/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponsePermissionResponse,
  ApiResponsePermissionResponse,
  ApiResponseVoid,
  DeleteBulkPermissionParams,
  FindAllPermissionParams,
  PermissionRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const findPermissionById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePermissionResponse>(
      {url: `/permissions/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFindPermissionByIdQueryKey = (id?: number,) => {
    return [
    `/permissions/${id}`
    ] as const;
    }

    
export const getFindPermissionByIdQueryOptions = <TData = Awaited<ReturnType<typeof findPermissionById>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindPermissionByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findPermissionById>>> = ({ signal }) => findPermissionById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindPermissionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findPermissionById>>>
export type FindPermissionByIdQueryError = ErrorType<unknown>


export function useFindPermissionById<TData = Awaited<ReturnType<typeof findPermissionById>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPermissionById>>,
          TError,
          Awaited<ReturnType<typeof findPermissionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindPermissionById<TData = Awaited<ReturnType<typeof findPermissionById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findPermissionById>>,
          TError,
          Awaited<ReturnType<typeof findPermissionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindPermissionById<TData = Awaited<ReturnType<typeof findPermissionById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindPermissionById<TData = Awaited<ReturnType<typeof findPermissionById>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findPermissionById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindPermissionByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updatePermission = (
    id: number,
    permissionRequest: BodyType<PermissionRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponsePermissionResponse>(
      {url: `/permissions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: permissionRequest
    },
      options);
    }
  


export const getUpdatePermissionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{id: number;data: BodyType<PermissionRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{id: number;data: BodyType<PermissionRequest>}, TContext> => {

const mutationKey = ['updatePermission'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePermission>>, {id: number;data: BodyType<PermissionRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePermission(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof updatePermission>>>
    export type UpdatePermissionMutationBody = BodyType<PermissionRequest>
    export type UpdatePermissionMutationError = ErrorType<unknown>

    export const useUpdatePermission = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{id: number;data: BodyType<PermissionRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePermission>>,
        TError,
        {id: number;data: BodyType<PermissionRequest>},
        TContext
      > => {

      const mutationOptions = getUpdatePermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePermissionById = (
    id: number,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/permissions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeletePermissionByIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermissionById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePermissionById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePermissionById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePermissionById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePermissionById(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePermissionByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deletePermissionById>>>
    
    export type DeletePermissionByIdMutationError = ErrorType<unknown>

    export const useDeletePermissionById = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermissionById>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePermissionById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePermissionByIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createPermission = (
    permissionRequest: BodyType<PermissionRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePermissionResponse>(
      {url: `/permissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: permissionRequest, signal
    },
      options);
    }
  


export const getCreatePermissionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPermission>>, TError,{data: BodyType<PermissionRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createPermission>>, TError,{data: BodyType<PermissionRequest>}, TContext> => {

const mutationKey = ['createPermission'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPermission>>, {data: BodyType<PermissionRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createPermission(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof createPermission>>>
    export type CreatePermissionMutationBody = BodyType<PermissionRequest>
    export type CreatePermissionMutationError = ErrorType<unknown>

    export const useCreatePermission = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPermission>>, TError,{data: BodyType<PermissionRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPermission>>,
        TError,
        {data: BodyType<PermissionRequest>},
        TContext
      > => {

      const mutationOptions = getCreatePermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAllPermission = (
    params?: FindAllPermissionParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponsePermissionResponse>(
      {url: `/permissions/all`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindAllPermissionQueryKey = (params?: FindAllPermissionParams,) => {
    return [
    `/permissions/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindAllPermissionQueryOptions = <TData = Awaited<ReturnType<typeof findAllPermission>>, TError = ErrorType<unknown>>(params?: FindAllPermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllPermissionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllPermission>>> = ({ signal }) => findAllPermission(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllPermissionQueryResult = NonNullable<Awaited<ReturnType<typeof findAllPermission>>>
export type FindAllPermissionQueryError = ErrorType<unknown>


export function useFindAllPermission<TData = Awaited<ReturnType<typeof findAllPermission>>, TError = ErrorType<unknown>>(
 params: undefined |  FindAllPermissionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllPermission>>,
          TError,
          Awaited<ReturnType<typeof findAllPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllPermission<TData = Awaited<ReturnType<typeof findAllPermission>>, TError = ErrorType<unknown>>(
 params?: FindAllPermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllPermission>>,
          TError,
          Awaited<ReturnType<typeof findAllPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllPermission<TData = Awaited<ReturnType<typeof findAllPermission>>, TError = ErrorType<unknown>>(
 params?: FindAllPermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllPermission<TData = Awaited<ReturnType<typeof findAllPermission>>, TError = ErrorType<unknown>>(
 params?: FindAllPermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllPermission>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllPermissionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteBulkPermission = (
    params: DeleteBulkPermissionParams,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/permissions/bulk`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBulkPermissionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkPermission>>, TError,{params: DeleteBulkPermissionParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBulkPermission>>, TError,{params: DeleteBulkPermissionParams}, TContext> => {

const mutationKey = ['deleteBulkPermission'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBulkPermission>>, {params: DeleteBulkPermissionParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteBulkPermission(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBulkPermissionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBulkPermission>>>
    
    export type DeleteBulkPermissionMutationError = ErrorType<unknown>

    export const useDeleteBulkPermission = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBulkPermission>>, TError,{params: DeleteBulkPermissionParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBulkPermission>>,
        TError,
        {params: DeleteBulkPermissionParams},
        TContext
      > => {

      const mutationOptions = getDeleteBulkPermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    