/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';






export const getUploadSignedUrlBody = zod.object({
  "originalName": zod.string().min(1),
  "contentType": zod.string().min(1),
  "purpose": zod.enum(['PROPERTY_FILE', 'PROPERTY_THUMBNAIL', 'PROPERTY_GALLERY', 'CHAT_FILE', 'AVATAR', 'CAROUSEL_IMAGE'])
})




export const getDownloadSignedUrlBody = zod.object({
  "objectKey": zod.string().min(1),
  "options": zod.string().optional()
})

export const deleteFile1Params = zod.object({
  "objectKey": zod.string()
})

