/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponsePresignedURLResponse,
  ApiResponsePresignedUploadResponse,
  ApiResponseVoid,
  PresignedDownloadRequest,
  PresignedUploadRequest
} from '../../types';

import { axiosInstanceFn } from '../../lib/axiosConfig';
import type { ErrorType , BodyType } from '../../lib/axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUploadSignedUrl = (
    presignedUploadRequest: BodyType<PresignedUploadRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePresignedUploadResponse>(
      {url: `/files/upload/signed-url`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedUploadRequest, signal
    },
      options);
    }
  


export const getGetUploadSignedUrlMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUploadSignedUrl>>, TError,{data: BodyType<PresignedUploadRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof getUploadSignedUrl>>, TError,{data: BodyType<PresignedUploadRequest>}, TContext> => {

const mutationKey = ['getUploadSignedUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUploadSignedUrl>>, {data: BodyType<PresignedUploadRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getUploadSignedUrl(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetUploadSignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof getUploadSignedUrl>>>
    export type GetUploadSignedUrlMutationBody = BodyType<PresignedUploadRequest>
    export type GetUploadSignedUrlMutationError = ErrorType<unknown>

    export const useGetUploadSignedUrl = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUploadSignedUrl>>, TError,{data: BodyType<PresignedUploadRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUploadSignedUrl>>,
        TError,
        {data: BodyType<PresignedUploadRequest>},
        TContext
      > => {

      const mutationOptions = getGetUploadSignedUrlMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getDownloadSignedUrl = (
    presignedDownloadRequest: BodyType<PresignedDownloadRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePresignedURLResponse>(
      {url: `/files/download/signed-url`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedDownloadRequest, signal
    },
      options);
    }
  


export const getGetDownloadSignedUrlMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getDownloadSignedUrl>>, TError,{data: BodyType<PresignedDownloadRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof getDownloadSignedUrl>>, TError,{data: BodyType<PresignedDownloadRequest>}, TContext> => {

const mutationKey = ['getDownloadSignedUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getDownloadSignedUrl>>, {data: BodyType<PresignedDownloadRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getDownloadSignedUrl(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetDownloadSignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof getDownloadSignedUrl>>>
    export type GetDownloadSignedUrlMutationBody = BodyType<PresignedDownloadRequest>
    export type GetDownloadSignedUrlMutationError = ErrorType<unknown>

    export const useGetDownloadSignedUrl = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getDownloadSignedUrl>>, TError,{data: BodyType<PresignedDownloadRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getDownloadSignedUrl>>,
        TError,
        {data: BodyType<PresignedDownloadRequest>},
        TContext
      > => {

      const mutationOptions = getGetDownloadSignedUrlMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteFile1 = (
    objectKey: string,
 options?: SecondParameter<typeof axiosInstanceFn>,) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/files/${objectKey}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteFile1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFile1>>, TError,{objectKey: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFile1>>, TError,{objectKey: string}, TContext> => {

const mutationKey = ['deleteFile1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFile1>>, {objectKey: string}> = (props) => {
          const {objectKey} = props ?? {};

          return  deleteFile1(objectKey,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFile1MutationResult = NonNullable<Awaited<ReturnType<typeof deleteFile1>>>
    
    export type DeleteFile1MutationError = ErrorType<unknown>

    export const useDeleteFile1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFile1>>, TError,{objectKey: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFile1>>,
        TError,
        {objectKey: string},
        TContext
      > => {

      const mutationOptions = getDeleteFile1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    