spring:
  config:
    activate:
      on-profile: pro
  datasource:
    url: jdbc:mysql://mysql:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    clean-disabled: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
